In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../../data/detail_jobs_202601111201.csv")
df.info()
df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2358 entries, 0 to 2357
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    2358 non-null   int64
 1   url_hash              2358 non-null   object
 2   job_url               2358 non-null   object
 3   title                 0 non-null      float64
 4   datetime              2358 non-null   object
 5   detail_title          2325 non-null   object
 6   detail_salary         2088 non-null   object
 7   detail_location       2173 non-null   object
 8   detail_experience     2173 non-null   object
 9   deadline              2237 non-null   object
 10  tags                  2325 non-null   object
 11  desc_mota             2173 non-null   object
 12  desc_yeucau           2173 non-null   object
 13  desc_quyenloi         2173 non-null   object
 14  working_addresses     2173 non-null   object
 15  working_times         1953 non-null   object
 16  company_url_from_job  2325 non-null   object
 17  general_info          2325 non-null   object
 18  box_categories        2325 non-null   object
dtypes: float64(1), int64(1), object(17)
memory usage: 350.1+ KB

,id,url_hash,job_url,title,datetime,detail_title,detail_salary,detail_location,detail_experience,deadline,tags,desc_mota,desc_yeucau,desc_quyenloi,working_addresses,working_times,company_url_from_job,general_info,box_categories
0,1,f42447711f5aaf8e629dd82f63f2ab83a40623326c180e...,viec-lam/python-developer-3-nam-kinh-nghiem/18...,NaN,2026-01-10 09:09:05.767,Python Developer - 3 Năm Kinh Nghiệm,Tới 30 triệu,Hà Nội,3 năm,31/01/2026,3 năm kinh nghiệm; Đại Học trở lên; Nghỉ thứ 7...,"Tham gia phát triển, xây dựng và duy trì hệ th...","Cử nhân chuyên ngành Công nghệ thông tin, Điện...",Offer: thỏa thuận theo năng lực (max upto 30M ...,"- Hà Nội: Ngô Sĩ Liên, Phường Đống Đa",Thứ 2 - Thứ 6 (từ 08:00 đến 17:00),https://www.topcv.vn/cong-ty/fecredit/81412.ht...,"{'Cấp bậc': 'Trưởng nhóm', 'Học vấn': 'Đại Học...","[{'box_title': 'Danh mục Nghề liên quan', 'cat..."
1,2,a122ed6ba9403f3a979b12b3d2a09cdd07314de2c8fc18...,viec-lam/quantitative-trading-intern-python-sq...,NaN,2026-01-10 09:09:13.804,"Quantitative Trading Intern ( Python , SQL )",2 - 2.4 triệu,Hồ Chí Minh (mới),Không yêu cầu,12/01/2026,Không yêu cầu kinh nghiệm; Đại Học trở lên; Ti...,Role Overview We are seeking a motivated and d...,Must-haves Senior student or graduated with a ...,Full-time internship allowance: 2.000000 VND/m...,"- Hồ Chí Minh: Phu My Hung Tower, 8 Hoàng Văn ...",Thứ 2 - Thứ 6 (từ 08:00 đến 17:00),https://www.topcv.vn/cong-ty/fecredit/81412.ht...,"{'Cấp bậc': 'Thực tập sinh', 'Học vấn': 'Đại H...","[{'box_title': 'Danh mục Nghề liên quan', 'cat..."
2,3,4ac21d9397c416dab626e9a0d2f7476f72cdbc7d87aadd...,viec-lam/fullstack-developer-net-python-nodejs...,NaN,2026-01-10 09:09:20.919,"Fullstack Developer (.Net, Python , NodeJS , R...",15 - 45 triệu,Hà Nội,1 năm,12/01/2026,1 năm kinh nghiệm; Trung cấp trở lên; Fullstac...,Chịu trách nhiệm phát triển Backend & Frontend...,Có tối thiểu 1 năm kinh nghiệm phát triển Back...,"Mức lương từ 15,000,000 đến 45,000.000 / tháng...","- Hà Nội: Số 32, ngõ 19 Hàm Nghi TP Hà Nội, Vi...",Thứ 2 - Thứ 6 (từ 08:30 đến 18:00); Thứ 7 (từ ...,https://www.topcv.vn/cong-ty/fecredit/81412.ht...,"{'Cấp bậc': 'Nhân viên', 'Học vấn': 'Trung cấp...","[{'box_title': 'Danh mục Nghề liên quan', 'cat..."
3,4,dd6e3c4d897458b348e1e855b168f17170ac6edb93742b...,viec-lam/lap-trinh-odoo-python/1962055.html,NaN,2026-01-10 09:09:28.063,Lập Trình Odoo ( Python ),15 - 25 triệu,Hà Nội,3 năm,24/01/2026,3 năm kinh nghiệm; Cao Đẳng trở lên; Nghỉ thứ ...,"Phát triển, tùy biến các module trên nền tảng ...",Nam/Nữ - Từ 23 tuổi trở lên Tốt nghiệp Đại học...,"Lương & thưởng: Thu nhập cạnh tranh, xét tăng ...","- Hà Nội: Tầng 5, Toà 32T - Đơn nguyên C, The ...",Thứ 2 - Thứ 6 (từ 08:00 đến 17:00),https://www.topcv.vn/cong-ty/fecredit/81412.ht...,"{'Cấp bậc': 'Trưởng nhóm', 'Học vấn': 'Cao Đẳn...","[{'box_title': 'Danh mục Nghề liên quan', 'cat..."
4,5,62b782393be08e53e8acd3f4b70cfdce09669f87c8df28...,brand/fptsoftwareacademy/tuyen-dung/junior-pyt...,NaN,2026-01-10 09:09:34.967,FPT Software,NaN,NaN,NaN,31/01/2026,Dưới 1 năm kinh nghiệm; Đại Học trở lên; Nghỉ ...,NaN,NaN,NaN,NaN,NaN,https://www.topcv.vn/cong-ty/fecredit/81412.ht...,{},[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2353,2499,08151933e4e99978f2316819a8b00fa515af8a09303168...,viec-lam/senior-brse/1568900.html,NaN,2026-01-11 04:36:13.378,Senior BrSE,Thoả thuận,Hồ Chí Minh (mới),4 năm,25/02/2026,4 năm kinh nghiệm; Đại Học trở lên; Kỹ sư cầu ...,Gia nhập Sun Asterisk HCM ngay – 50 triệu về t...,1. Attitude Tính chủ động cao trong công việc ...,"Môi trường chuyên nghiệp, cởi mở, đề cao sự sá...","- Hồ Chí Minh: Tầng 9 và Tầng 10, L'Mak Long T...",NaN,https://www.topcv.vn/cong-ty/fecredit/81412.ht...,"{'Cấp bậc': 'Nhân viên', 'Học vấn': 'Đại Học t...","[{'box_title': 'Danh mục Nghề liên quan', 'cat..."
2354,2500,811e90b5cecb6065fccf93e911747a3f25b5d2446e38fa...,viec-lam/bridge-coordinator-japanese-n2-quan-7...,NaN,2026-01-11 04:36:51.244,"Bridge Coordinator (Japanese N2) - Quận 7 , HCM",Thoả thuận,Hồ Chí Minh (mới),2 năm,11/01/2026,2 năm kinh nghiệm; Đại Học trở lên; Tuổi 27 - ...,- Chat bằng tiếng Nhật với người phụ trách ngư...,・Tốt nghiệp đại học . ・Trình độ tiếng Nhật N2 ...,"- Tăng lương 1 lần/năm, Thưởng 1 lần/năm - Phụ...",- Hồ Chí Minh: Phường Tân Mỹ,Thứ 2 - Thứ 7 (từ 08:00 đến 17:00),https://www.topcv.vn/cong-ty/fecredit/81412.ht...,"{'Cấp bậc': 'Nhân viên', 'Học vấn': 'Đại Học t...","[{'box_title': 'Danh mục Nghề liên quan', 'cat..."
2355,2501,588916068a2c029987bbd6d64c57f7eb4008c436f78a84...,viec-lam/ky-su-cau-noi-brse-tieng-han/1992176....,NaN,2026-01-11 04:37:22.805,Kỹ Sư Cầu Nối ( BrSE Tiếng Hàn ),Thoả thuận,Hồ Chí Minh (mới),1 năm,21/01/2026,1 năm kinh nghiệm; Đại Học trở lên; Nghỉ thứ 7...,Tham gia vào các dự án outsource cho khách hàn...,Ưu tiên ứng viên tốt nghiệp Đại học/Cao đẳng h...,Lương: UPTO $1800 GROSS (deal theo vị trí và n...,- Hồ Chí Minh: Phường Tân Sơn Hòa,Thứ 2 - Thứ 6 (từ 08:00 đến 12:00); Thứ 2 - Th...,https://www.topcv.vn/cong-ty/fecredit/81412.ht...,"{'Cấp bậc': 'Nhân viên', 'Học vấn': 'Đại Học t...","[{'box_title': 'Danh mục Nghề liên quan', 'cat..."
2356,2502,91424afea7df78823bdc6f20aa77797c584d4031d54b43...,viec-lam/ky-su-cau-noi-brse-ba-dinh-ha-noi-upt...,NaN,2026-01-11 04:38:00.775,"Kỹ Sư Cầu Nối BrSE - Ba Đình, Hà Nội - Upto 60...",40 - 60 triệu,Hà Nội,5 năm,30/01/2026,5 năm kinh nghiệm; Đại Học trở lên; Tuổi 34 - ...,• Nghiên cứu và truyền đạt chính xác kiến ​​th...,- Bằng cử nhân hoặc tương đương trong lĩnh vực...,- Bảo hiểm xã hội/y tế theo quy định của pháp ...,- Hà Nội: Phường Ba Đình,Thứ 2 - Thứ 6 (từ 08:00 đến 17:00),https://www.topcv.vn/cong-ty/fecredit/81412.ht...,"{'Cấp bậc': 'Nhân viên', 'Học vấn': 'Đại Học t...","[{'box_title': 'Danh mục Nghề liên quan', 'cat..."
2357,2503,6120b16f74c724312ade451bc758d0fb61f7ce8175f4c6...,viec-lam/ky-su-cau-noi-khong-yc-base-tech-ob-s...,NaN,2026-01-11 04:38:39.630,"Kỹ Sư Cầu Nối (Không Yc Base Tech, OB Sau Tết)",30 - 40 triệu,Hà Nội,1 năm,30/04/2026,1 năm kinh nghiệm; Đại Học trở lên; Nghỉ thứ 7...,"Làm BrSE cho dự án với khách hàng Nhật, trực t...","Tiếng Nhật JLPT N2 trở lên, giao tiếp tốt Kinh...","a. Thu nhập: Lương cạnh tranh, thỏa đáng theo ...","- Hà Nội: Tòa 6th Element Nguyễn Văn Huyên, Ph...",Thứ 2 - Thứ 6 (từ 08:30 đến 17:30),https://www.topcv.vn/cong-ty/fecredit/81412.ht...,"{'Cấp bậc': 'Nhân viên', 'Học vấn': 'Đại Học t...","[{'box_title': 'Danh mục Nghề liên quan', 'cat..."

# Parse detail salary

In [3]:
salary_df = df["detail_salary"].copy()
salary_df = salary_df.drop_duplicates().reset_index(drop=True)
salary_df = salary_df.to_frame()
salary_df

      detail_salary
0      Tới 30 triệu
1     2 - 2.4 triệu
2     15 - 45 triệu
3     15 - 25 triệu
4               NaN
..              ...
279    Từ 2,000 USD
280   11 - 17 triệu
281   30 - 70 triệu
282  65 - 105 triệu
283   20 - 37 triệu

[284 rows x 1 columns]

In [28]:
import re
def parse_salary(salary_str):
    if pd.isna(salary_str):
        return None, None,None

    salary_str = salary_str.replace(",", "").strip()
    if "Thỏa thuận" in salary_str:
        return None, None,None
    
    currency = None
    if "USD" in salary_str:
        currency = "USD"
    if "triệu" in salary_str: 
        currency = "trieu VND"
    
    numbers = [float(s) for s in re.findall(r'\d+(?:.\d+)?', salary_str)]

    if "Từ" in salary_str:
        min_salary = numbers[0]
        return min_salary, None,currency
    
    if "Tới" in salary_str:
        max_salary = numbers[0]
        return None, max_salary,currency
    
    if "-" in salary_str:
        min_salary = numbers[0]
        max_salary = numbers[1]
        return min_salary, max_salary,currency
    
    return None, None, None

In [29]:
print(parse_salary("Tới 2,000 USD"))  # (500.0, None)

(None, 2000.0, 'USD')

In [30]:
salary_df['min_salary'], salary_df['max_salary'],salary_df['currency'] = zip(*salary_df['detail_salary'].apply(parse_salary))

In [31]:
salary_df

      detail_salary  min_salary  max_salary   currency
0      Tới 30 triệu         NaN        30.0  trieu VND
1     2 - 2.4 triệu         2.0         2.4  trieu VND
2     15 - 45 triệu        15.0        45.0  trieu VND
3     15 - 25 triệu        15.0        25.0  trieu VND
4               NaN         NaN         NaN       None
..              ...         ...         ...        ...
279    Từ 2,000 USD      2000.0         NaN        USD
280   11 - 17 triệu        11.0        17.0  trieu VND
281   30 - 70 triệu        30.0        70.0  trieu VND
282  65 - 105 triệu        65.0       105.0  trieu VND
283   20 - 37 triệu        20.0        37.0  trieu VND

[284 rows x 4 columns]

# Parse experience

In [22]:
expericence_df = df["detail_experience"].copy()
expericence_df = expericence_df.drop_duplicates().reset_index(drop=True)
expericence_df = expericence_df.to_frame()
expericence_df

  detail_experience
0             3 năm
1     Không yêu cầu
2             1 năm
3               NaN
4             2 năm
5             4 năm
6        Dưới 1 năm
7             5 năm
8        Trên 5 năm

Có thể là những job dưới 1 năm kinh nghiệm là fresher
con những job không yêu cầu kinh nghiệm là internship

In [ ]:
def parse_experience(exp_str):
    if pd.isna(exp_str):
        return None

    exp_str = exp_str.replace("năm", "").strip()
    if "Không yêu cầu" in exp_str:
        return 0

    if "Dưới 1" in exp_str:
        return 0.5
    
    if "Trên 5" in exp_str:
        return 7
    
    numbers = [float(s) for s in re.findall(r'\d+(?:\.\d+)?', exp_str)]

    return numbers[0]

In [37]:
expericence_df["min_experience"] = expericence_df['detail_experience'].apply(parse_experience)
expericence_df

  detail_experience  min_experience
0             3 năm             3.0
1     Không yêu cầu             0.0
2             1 năm             1.0
3               NaN             NaN
4             2 năm             2.0
5             4 năm             4.0
6        Dưới 1 năm             0.5
7             5 năm             5.0
8        Trên 5 năm             7.0

# Parse Working time

In [39]:
wt_df = df["working_times"].copy()
wt_df = wt_df.drop_duplicates().reset_index(drop=True)
wt_df = wt_df.to_frame()
wt_df

                                         working_times
0                   Thứ 2 - Thứ 6 (từ 08:00 đến 17:00)
1    Thứ 2 - Thứ 6 (từ 08:30 đến 18:00); Thứ 7 (từ ...
2                                                  NaN
3                   Thứ 2 - Thứ 6 (từ 08:30 đến 17:30)
4                   Thứ 2 - Thứ 6 (từ 07:50 đến 17:30)
..                                                 ...
655  Thứ 2 - Thứ 6 (từ 00:00 đến 00:00); Checkin li...
656  Thứ 2 đến sáng thứ 7: 8h00 - 12h00, 13h30 - 17h30
657  Thứ 2 - Thứ 6 (từ 08:30 đến 17:45); Linh hoạt,...
658  Thứ 2 - Thứ 6 (từ 08:00 đến 17:00); Làm việc t...
659  Thứ 2 - Thứ 6 (từ 08:00 đến 12:00); Thứ 2 - Th...

[660 rows x 1 columns]

In [42]:
import re
def parse_working_time(wt_str):
    if pd.isna(wt_str):
        return None

    wt_str = wt_str.strip().lower()
    if "thứ 2 - thứ 6" in wt_str:
        return 5
    if "thứ 2 - thứ 7" in wt_str:
        return 6
    if "thứ 2 - chủ nhật" in wt_str:
        return 7
    return "Other"

In [43]:
wt_df["parsed_working_days"] = wt_df['working_times'].apply(parse_working_time)
wt_df

                                         working_times parsed_working_days
0                   Thứ 2 - Thứ 6 (từ 08:00 đến 17:00)                   5
1    Thứ 2 - Thứ 6 (từ 08:30 đến 18:00); Thứ 7 (từ ...                   5
2                                                  NaN                None
3                   Thứ 2 - Thứ 6 (từ 08:30 đến 17:30)                   5
4                   Thứ 2 - Thứ 6 (từ 07:50 đến 17:30)                   5
..                                                 ...                 ...
655  Thứ 2 - Thứ 6 (từ 00:00 đến 00:00); Checkin li...                   5
656  Thứ 2 đến sáng thứ 7: 8h00 - 12h00, 13h30 - 17h30               Other
657  Thứ 2 - Thứ 6 (từ 08:30 đến 17:45); Linh hoạt,...                   5
658  Thứ 2 - Thứ 6 (từ 08:00 đến 17:00); Làm việc t...                   5
659  Thứ 2 - Thứ 6 (từ 08:00 đến 12:00); Thứ 2 - Th...                   5

[660 rows x 2 columns]

In [44]:
df["parsed_working_days"] = df["working_times"].apply(parse_working_time)
df

,id,url_hash,job_url,title,datetime,detail_title,detail_salary,detail_location,detail_experience,deadline,tags,desc_mota,desc_yeucau,desc_quyenloi,working_addresses,working_times,company_url_from_job,general_info,box_categories,parsed_working_days
0,1,f42447711f5aaf8e629dd82f63f2ab83a40623326c180e...,viec-lam/python-developer-3-nam-kinh-nghiem/18...,NaN,2026-01-10 09:09:05.767,Python Developer - 3 Năm Kinh Nghiệm,Tới 30 triệu,Hà Nội,3 năm,31/01/2026,3 năm kinh nghiệm; Đại Học trở lên; Nghỉ thứ 7...,"Tham gia phát triển, xây dựng và duy trì hệ th...","Cử nhân chuyên ngành Công nghệ thông tin, Điện...",Offer: thỏa thuận theo năng lực (max upto 30M ...,"- Hà Nội: Ngô Sĩ Liên, Phường Đống Đa",Thứ 2 - Thứ 6 (từ 08:00 đến 17:00),https://www.topcv.vn/cong-ty/fecredit/81412.ht...,"{'Cấp bậc': 'Trưởng nhóm', 'Học vấn': 'Đại Học...","[{'box_title': 'Danh mục Nghề liên quan', 'cat...",5
1,2,a122ed6ba9403f3a979b12b3d2a09cdd07314de2c8fc18...,viec-lam/quantitative-trading-intern-python-sq...,NaN,2026-01-10 09:09:13.804,"Quantitative Trading Intern ( Python , SQL )",2 - 2.4 triệu,Hồ Chí Minh (mới),Không yêu cầu,12/01/2026,Không yêu cầu kinh nghiệm; Đại Học trở lên; Ti...,Role Overview We are seeking a motivated and d...,Must-haves Senior student or graduated with a ...,Full-time internship allowance: 2.000000 VND/m...,"- Hồ Chí Minh: Phu My Hung Tower, 8 Hoàng Văn ...",Thứ 2 - Thứ 6 (từ 08:00 đến 17:00),https://www.topcv.vn/cong-ty/fecredit/81412.ht...,"{'Cấp bậc': 'Thực tập sinh', 'Học vấn': 'Đại H...","[{'box_title': 'Danh mục Nghề liên quan', 'cat...",5
2,3,4ac21d9397c416dab626e9a0d2f7476f72cdbc7d87aadd...,viec-lam/fullstack-developer-net-python-nodejs...,NaN,2026-01-10 09:09:20.919,"Fullstack Developer (.Net, Python , NodeJS , R...",15 - 45 triệu,Hà Nội,1 năm,12/01/2026,1 năm kinh nghiệm; Trung cấp trở lên; Fullstac...,Chịu trách nhiệm phát triển Backend & Frontend...,Có tối thiểu 1 năm kinh nghiệm phát triển Back...,"Mức lương từ 15,000,000 đến 45,000.000 / tháng...","- Hà Nội: Số 32, ngõ 19 Hàm Nghi TP Hà Nội, Vi...",Thứ 2 - Thứ 6 (từ 08:30 đến 18:00); Thứ 7 (từ ...,https://www.topcv.vn/cong-ty/fecredit/81412.ht...,"{'Cấp bậc': 'Nhân viên', 'Học vấn': 'Trung cấp...","[{'box_title': 'Danh mục Nghề liên quan', 'cat...",5
3,4,dd6e3c4d897458b348e1e855b168f17170ac6edb93742b...,viec-lam/lap-trinh-odoo-python/1962055.html,NaN,2026-01-10 09:09:28.063,Lập Trình Odoo ( Python ),15 - 25 triệu,Hà Nội,3 năm,24/01/2026,3 năm kinh nghiệm; Cao Đẳng trở lên; Nghỉ thứ ...,"Phát triển, tùy biến các module trên nền tảng ...",Nam/Nữ - Từ 23 tuổi trở lên Tốt nghiệp Đại học...,"Lương & thưởng: Thu nhập cạnh tranh, xét tăng ...","- Hà Nội: Tầng 5, Toà 32T - Đơn nguyên C, The ...",Thứ 2 - Thứ 6 (từ 08:00 đến 17:00),https://www.topcv.vn/cong-ty/fecredit/81412.ht...,"{'Cấp bậc': 'Trưởng nhóm', 'Học vấn': 'Cao Đẳn...","[{'box_title': 'Danh mục Nghề liên quan', 'cat...",5
4,5,62b782393be08e53e8acd3f4b70cfdce09669f87c8df28...,brand/fptsoftwareacademy/tuyen-dung/junior-pyt...,NaN,2026-01-10 09:09:34.967,FPT Software,NaN,NaN,NaN,31/01/2026,Dưới 1 năm kinh nghiệm; Đại Học trở lên; Nghỉ ...,NaN,NaN,NaN,NaN,NaN,https://www.topcv.vn/cong-ty/fecredit/81412.ht...,{},[],None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2353,2499,08151933e4e99978f2316819a8b00fa515af8a09303168...,viec-lam/senior-brse/1568900.html,NaN,2026-01-11 04:36:13.378,Senior BrSE,Thoả thuận,Hồ Chí Minh (mới),4 năm,25/02/2026,4 năm kinh nghiệm; Đại Học trở lên; Kỹ sư cầu ...,Gia nhập Sun Asterisk HCM ngay – 50 triệu về t...,1. Attitude Tính chủ động cao trong công việc ...,"Môi trường chuyên nghiệp, cởi mở, đề cao sự sá...","- Hồ Chí Minh: Tầng 9 và Tầng 10, L'Mak Long T...",NaN,https://www.topcv.vn/cong-ty/fecredit/81412.ht...,"{'Cấp bậc': 'Nhân viên', 'Học vấn': 'Đại Học t...","[{'box_title': 'Danh mục Nghề liên quan', 'cat...",None
2354,2500,811e90b5cecb6065fccf93e911747a3f25b5d2446e38fa...,viec-lam/bridge-coordinator-japanese-n2-quan-7...,NaN,2026-01-11 04:36:51.244,"Bridge Coordinator (Japanese N2) - Quận 7 , HCM",Thoả thuận,Hồ Chí Minh (mới),2 năm,11/01/2026,2 năm kinh nghiệm; Đại Học trở lên; Tuổi 27 - ...,- Chat bằng tiếng Nhật với người phụ trách ngư...,・Tốt nghiệp đại học . ・Trình độ tiếng Nhật N2 ...,"- Tăng lương 1 lần/năm, Thưởng 1 lần/năm - Phụ...",- Hồ Chí Minh: Phường Tân Mỹ,Thứ 2 - Thứ 7 (từ 08:00 đến 17:00),https://www.topcv.vn/cong-ty/fecredit/81412.ht...,"{'Cấp bậc': 'Nhân viên', 'Học vấn': 'Đại Học t...","[{'box_title': 'Danh mục Nghề liên quan', 'cat...",6
2355,2501,588916068a2c029987bbd6d64c57f7eb4008c436f78a84...,viec-lam/ky-su-cau-noi-brse-tieng-han/1992176....,NaN,2026-01-11 04:37:22.805,Kỹ Sư Cầu Nối ( BrSE Tiếng Hàn ),Thoả thuận,Hồ Chí Minh (mới),1 năm,21/01/2026,1 năm kinh nghiệm; Đại Học trở lên; Nghỉ thứ 7...,Tham gia vào các dự án outsource cho khách hàn...,Ưu tiên ứng viên tốt nghiệp Đại học/Cao đẳng h...,Lương: UPTO $1800 GROSS (deal theo vị trí và n...,- Hồ Chí Minh: Phường Tân Sơn Hòa,Thứ 2 - Thứ 6 (từ 08:00 đến 12:00); Thứ 2 - Th...,https://www.topcv.vn/cong-ty/fecredit/81412.ht...,"{'Cấp bậc': 'Nhân viên', 'Học vấn': 'Đại Học t...","[{'box_title': 'Danh mục Nghề liên quan', 'cat...",5
2356,2502,91424afea7df78823bdc6f20aa77797c584d4031d54b43...,viec-lam/ky-su-cau-noi-brse-ba-dinh-ha-noi-upt...,NaN,2026-01-11 04:38:00.775,"Kỹ Sư Cầu Nối BrSE - Ba Đình, Hà Nội - Upto 60...",40 - 60 triệu,Hà Nội,5 năm,30/01/2026,5 năm kinh nghiệm; Đại Học trở lên; Tuổi 34 - ...,• Nghiên cứu và truyền đạt chính xác kiến ​​th...,- Bằng cử nhân hoặc tương đương trong lĩnh vực...,- Bảo hiểm xã hội/y tế theo quy định của pháp ...,- Hà Nội: Phường Ba Đình,Thứ 2 - Thứ 6 (từ 08:00 đến 17:00),https://www.topcv.vn/cong-ty/fecredit/81412.ht...,"{'Cấp bậc': 'Nhân viên', 'Học vấn': 'Đại Học t...","[{'box_title': 'Danh mục Nghề liên quan', 'cat...",5
2357,2503,6120b16f74c724312ade451bc758d0fb61f7ce8175f4c6...,viec-lam/ky-su-cau-noi-khong-yc-base-tech-ob-s...,NaN,2026-01-11 04:38:39.630,"Kỹ Sư Cầu Nối (Không Yc Base Tech, OB Sau Tết)",30 - 40 triệu,Hà Nội,1 năm,30/04/2026,1 năm kinh nghiệm; Đại Học trở lên; Nghỉ thứ 7...,"Làm BrSE cho dự án với khách hàng Nhật, trực t...","Tiếng Nhật JLPT N2 trở lên, giao tiếp tốt Kinh...","a. Thu nhập: Lương cạnh tranh, thỏa đáng theo ...","- Hà Nội: Tòa 6th Element Nguyễn Văn Huyên, Ph...",Thứ 2 - Thứ 6 (từ 08:30 đến 17:30),https://www.topcv.vn/cong-ty/fecredit/81412.ht...,"{'Cấp bậc': 'Nhân viên', 'Học vấn': 'Đại Học t...","[{'box_title': 'Danh mục Nghề liên quan', 'cat...",5

# Parse general info

In [3]:
general_info_df = df[["general_info"]].copy()
general_info_df

                                           general_info
0     {'Cấp bậc': 'Trưởng nhóm', 'Học vấn': 'Đại Học...
1     {'Cấp bậc': 'Thực tập sinh', 'Học vấn': 'Đại H...
2     {'Cấp bậc': 'Nhân viên', 'Học vấn': 'Trung cấp...
3     {'Cấp bậc': 'Trưởng nhóm', 'Học vấn': 'Cao Đẳn...
4                                                    {}
...                                                 ...
2353  {'Cấp bậc': 'Nhân viên', 'Học vấn': 'Đại Học t...
2354  {'Cấp bậc': 'Nhân viên', 'Học vấn': 'Đại Học t...
2355  {'Cấp bậc': 'Nhân viên', 'Học vấn': 'Đại Học t...
2356  {'Cấp bậc': 'Nhân viên', 'Học vấn': 'Đại Học t...
2357  {'Cấp bậc': 'Nhân viên', 'Học vấn': 'Đại Học t...

[2358 rows x 1 columns]

In [10]:
import ast
def parse_general_info(info_str):
    if pd.isna(info_str):
        return {}
    try:
        info_dict = ast.literal_eval(info_str)
        if isinstance(info_dict, dict):
            return info_dict
        else:
            return {}
    except (ValueError, SyntaxError):
        return {}

In [11]:
general_info_df["parsed_general_info"] = general_info_df['general_info'].apply(parse_general_info)
general_info_df

,general_info,0,parsed_general_info
0,"{'Cấp bậc': 'Trưởng nhóm', 'Học vấn': 'Đại Học...","{'Cấp bậc': 'Trưởng nhóm', 'Học vấn': 'Đại Học...","{'Cấp bậc': 'Trưởng nhóm', 'Học vấn': 'Đại Học..."
1,"{'Cấp bậc': 'Thực tập sinh', 'Học vấn': 'Đại H...","{'Cấp bậc': 'Thực tập sinh', 'Học vấn': 'Đại H...","{'Cấp bậc': 'Thực tập sinh', 'Học vấn': 'Đại H..."
2,"{'Cấp bậc': 'Nhân viên', 'Học vấn': 'Trung cấp...","{'Cấp bậc': 'Nhân viên', 'Học vấn': 'Trung cấp...","{'Cấp bậc': 'Nhân viên', 'Học vấn': 'Trung cấp..."
3,"{'Cấp bậc': 'Trưởng nhóm', 'Học vấn': 'Cao Đẳn...","{'Cấp bậc': 'Trưởng nhóm', 'Học vấn': 'Cao Đẳn...","{'Cấp bậc': 'Trưởng nhóm', 'Học vấn': 'Cao Đẳn..."
4,{},{},{}
...,...,...,...
2353,"{'Cấp bậc': 'Nhân viên', 'Học vấn': 'Đại Học t...","{'Cấp bậc': 'Nhân viên', 'Học vấn': 'Đại Học t...","{'Cấp bậc': 'Nhân viên', 'Học vấn': 'Đại Học t..."
2354,"{'Cấp bậc': 'Nhân viên', 'Học vấn': 'Đại Học t...","{'Cấp bậc': 'Nhân viên', 'Học vấn': 'Đại Học t...","{'Cấp bậc': 'Nhân viên', 'Học vấn': 'Đại Học t..."
2355,"{'Cấp bậc': 'Nhân viên', 'Học vấn': 'Đại Học t...","{'Cấp bậc': 'Nhân viên', 'Học vấn': 'Đại Học t...","{'Cấp bậc': 'Nhân viên', 'Học vấn': 'Đại Học t..."
2356,"{'Cấp bậc': 'Nhân viên', 'Học vấn': 'Đại Học t...","{'Cấp bậc': 'Nhân viên', 'Học vấn': 'Đại Học t...","{'Cấp bậc': 'Nhân viên', 'Học vấn': 'Đại Học t..."
2357,"{'Cấp bậc': 'Nhân viên', 'Học vấn': 'Đại Học t...","{'Cấp bậc': 'Nhân viên', 'Học vấn': 'Đại Học t...","{'Cấp bậc': 'Nhân viên', 'Học vấn': 'Đại Học t..."

In [12]:
general_info_expand = general_info_df['parsed_general_info'].apply(pd.Series)

In [14]:
general_info_df = pd.concat([general_info_df, general_info_expand], axis=1)
general_info_df

,general_info,0,parsed_general_info,Cấp bậc,Học vấn,Số lượng tuyển,Hình thức làm việc
0,"{'Cấp bậc': 'Trưởng nhóm', 'Học vấn': 'Đại Học...","{'Cấp bậc': 'Trưởng nhóm', 'Học vấn': 'Đại Học...","{'Cấp bậc': 'Trưởng nhóm', 'Học vấn': 'Đại Học...",Trưởng nhóm,Đại Học trở lên,1 người,Toàn thời gian
1,"{'Cấp bậc': 'Thực tập sinh', 'Học vấn': 'Đại H...","{'Cấp bậc': 'Thực tập sinh', 'Học vấn': 'Đại H...","{'Cấp bậc': 'Thực tập sinh', 'Học vấn': 'Đại H...",Thực tập sinh,Đại Học trở lên,1 người,Thực tập
2,"{'Cấp bậc': 'Nhân viên', 'Học vấn': 'Trung cấp...","{'Cấp bậc': 'Nhân viên', 'Học vấn': 'Trung cấp...","{'Cấp bậc': 'Nhân viên', 'Học vấn': 'Trung cấp...",Nhân viên,Trung cấp trở lên,3 người,Toàn thời gian
3,"{'Cấp bậc': 'Trưởng nhóm', 'Học vấn': 'Cao Đẳn...","{'Cấp bậc': 'Trưởng nhóm', 'Học vấn': 'Cao Đẳn...","{'Cấp bậc': 'Trưởng nhóm', 'Học vấn': 'Cao Đẳn...",Trưởng nhóm,Cao Đẳng trở lên,1 người,Toàn thời gian
4,{},{},{},NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...
2353,"{'Cấp bậc': 'Nhân viên', 'Học vấn': 'Đại Học t...","{'Cấp bậc': 'Nhân viên', 'Học vấn': 'Đại Học t...","{'Cấp bậc': 'Nhân viên', 'Học vấn': 'Đại Học t...",Nhân viên,Đại Học trở lên,2 người,Toàn thời gian
2354,"{'Cấp bậc': 'Nhân viên', 'Học vấn': 'Đại Học t...","{'Cấp bậc': 'Nhân viên', 'Học vấn': 'Đại Học t...","{'Cấp bậc': 'Nhân viên', 'Học vấn': 'Đại Học t...",Nhân viên,Đại Học trở lên,1 người,Toàn thời gian
2355,"{'Cấp bậc': 'Nhân viên', 'Học vấn': 'Đại Học t...","{'Cấp bậc': 'Nhân viên', 'Học vấn': 'Đại Học t...","{'Cấp bậc': 'Nhân viên', 'Học vấn': 'Đại Học t...",Nhân viên,Đại Học trở lên,1 người,Toàn thời gian
2356,"{'Cấp bậc': 'Nhân viên', 'Học vấn': 'Đại Học t...","{'Cấp bậc': 'Nhân viên', 'Học vấn': 'Đại Học t...","{'Cấp bậc': 'Nhân viên', 'Học vấn': 'Đại Học t...",Nhân viên,Đại Học trở lên,1 người,Toàn thời gian
2357,"{'Cấp bậc': 'Nhân viên', 'Học vấn': 'Đại Học t...","{'Cấp bậc': 'Nhân viên', 'Học vấn': 'Đại Học t...","{'Cấp bậc': 'Nhân viên', 'Học vấn': 'Đại Học t...",Nhân viên,Đại Học trở lên,2 người,Toàn thời gian

# Parse box categories

In [15]:
box_categories_df = df[["box_categories"]].copy()
box_categories_df

                                         box_categories
0     [{'box_title': 'Danh mục Nghề liên quan', 'cat...
1     [{'box_title': 'Danh mục Nghề liên quan', 'cat...
2     [{'box_title': 'Danh mục Nghề liên quan', 'cat...
3     [{'box_title': 'Danh mục Nghề liên quan', 'cat...
4                                                    []
...                                                 ...
2353  [{'box_title': 'Danh mục Nghề liên quan', 'cat...
2354  [{'box_title': 'Danh mục Nghề liên quan', 'cat...
2355  [{'box_title': 'Danh mục Nghề liên quan', 'cat...
2356  [{'box_title': 'Danh mục Nghề liên quan', 'cat...
2357  [{'box_title': 'Danh mục Nghề liên quan', 'cat...

[2358 rows x 1 columns]

In [16]:
def parse_box_categories(box_str):
    if pd.isna(box_str):
        return {}
    try:
        parse_box = {}
        box_list = ast.literal_eval(box_str)
        if isinstance(box_list, list):
            for item in box_list:
                if isinstance(item, dict) and 'box_title' in item and 'categories' in item:
                    parse_box.update({item['box_title'] : item['categories']})
            return parse_box
        else:
            return {}
    except (ValueError, SyntaxError):
        return {}

In [17]:
box_categories_df["box_categories_parsed"] = box_categories_df['box_categories'].apply(parse_box_categories)
box_categories_df

,box_categories,box_categories_parsed
0,"[{'box_title': 'Danh mục Nghề liên quan', 'cat...",{'Danh mục Nghề liên quan': ['Công nghệ Thông ...
1,"[{'box_title': 'Danh mục Nghề liên quan', 'cat...",{'Danh mục Nghề liên quan': ['Marketing/PR/Quả...
2,"[{'box_title': 'Danh mục Nghề liên quan', 'cat...",{'Danh mục Nghề liên quan': ['Công nghệ Thông ...
3,"[{'box_title': 'Danh mục Nghề liên quan', 'cat...",{'Danh mục Nghề liên quan': ['Công nghệ Thông ...
4,[],{}
...,...,...
2353,"[{'box_title': 'Danh mục Nghề liên quan', 'cat...",{'Danh mục Nghề liên quan': ['Công nghệ Thông ...
2354,"[{'box_title': 'Danh mục Nghề liên quan', 'cat...",{'Danh mục Nghề liên quan': ['Công nghệ Thông ...
2355,"[{'box_title': 'Danh mục Nghề liên quan', 'cat...",{'Danh mục Nghề liên quan': ['Công nghệ Thông ...
2356,"[{'box_title': 'Danh mục Nghề liên quan', 'cat...",{'Danh mục Nghề liên quan': ['Công nghệ Thông ...
2357,"[{'box_title': 'Danh mục Nghề liên quan', 'cat...",{'Danh mục Nghề liên quan': ['Công nghệ Thông ...

In [18]:
box_categories_expand_df= box_categories_df['box_categories_parsed'].apply(pd.Series)
box_categories_expand_df

,Danh mục Nghề liên quan,Kỹ năng cần có,Khu vực,Kỹ năng nên có
0,"[Công nghệ Thông tin, Software Engineering, So...","[Python, Kiểm Soát Phiên Bản (git), Lập Trình ...","[Hà Nội, Phường Đống Đa - Hà Nội]",NaN
1,"[Marketing/PR/Quảng cáo, Công nghệ Thông tin, ...","[Python, SQL, pandas, numpy, logical thinking,...","[Hồ Chí Minh, Phường Tân Mỹ - Hồ Chí Minh]","[Backtrader, Zipline, Machine Learning, Time-s..."
2,"[Công nghệ Thông tin, Software Engineering, Fu...","[.NET, Bootstrap, Javascript, Python, ReactJS,...","[Hà Nội, Phường Từ Liêm - Hà Nội]","[AngularJS, NodeJS, Docker]"
3,"[Công nghệ Thông tin, Software Engineering, Ba...","[Javascript, Python, SQL, HTML/CSS, Version Co...","[Hà Nội, Xã Hoài Đức - Hà Nội]","[RESTful APIs, Testing (unit, Integration), Ui..."
4,NaN,NaN,NaN,NaN
...,...,...,...,...
2353,"[Công nghệ Thông tin, IT Project Management, K...","[Problem-solving, business analysis, Communica...","[Hồ Chí Minh, Phường Bình Thạnh - Hồ Chí Minh]",NaN
2354,"[Công nghệ Thông tin, IT Project Management, K...",[phiên dịch IT],"[Hồ Chí Minh, Phường Tân Mỹ - Hồ Chí Minh]",NaN
2355,"[Công nghệ Thông tin, IT Project Management, K...","[Tiếng Hàn (topik), Kỹ Năng Cầu Nối (brse), Ti...","[Hồ Chí Minh, Phường Tân Sơn Hòa - Hồ Chí Minh]",NaN
2356,"[Công nghệ Thông tin, IT Project Management, K...",NaN,"[Hà Nội, Phường Ba Đình - Hà Nội]",NaN
2357,"[Công nghệ Thông tin, IT Project Management, K...",[Tiếng Nhật],"[Hà Nội, Phường Nghĩa Đô - Hà Nội]",[Kinh Nghiệm Làm Việc Với Khách Hàng Nhật Bản]