In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd

process_merged_df = pd.read_csv("/content/drive/MyDrive/Classroom/DATN/data/checkpoint_NER_1.csv")

In [ ]:
process_merged_df

,Unnamed: 0,job_id,skills,id,detail_title,desc_mota,desc_yeucau,general_info,box_categories,TECH_SKILL,KNOWLEDGE
0,0,1,"{'TECH_SKILL': ['Python', 'Microservices', 'Do...",1,Python Developer - 3 Năm Kinh Nghiệm,"Tham gia phát triển, xây dựng và duy trì hệ th...","Cử nhân chuyên ngành Công nghệ thông tin, Điện...","{'Cấp bậc': 'Trưởng nhóm', 'Học vấn': 'Đại Học...","[{'box_title': 'Danh mục Nghề liên quan', 'cat...","['Python', 'Microservices', 'Docker', 'Kuberne...",['Frontend (ReactJS)']
1,1,2,"{'TECH_SKILL': ['Python', 'SQL', 'Pandas', 'Nu...",2,"Quantitative Trading Intern ( Python , SQL )",Role Overview We are seeking a motivated and d...,Must-haves Senior student or graduated with a ...,"{'Cấp bậc': 'Thực tập sinh', 'Học vấn': 'Đại H...","[{'box_title': 'Danh mục Nghề liên quan', 'cat...","['Python', 'SQL', 'Pandas', 'NumPy', 'Backtrad...","['Quantitative Trading', 'Financial Markets', ..."
2,2,3,"{'TECH_SKILL': ['.Net', 'Python', 'JavaScript'...",3,"Fullstack Developer (.Net, Python , NodeJS , R...",Chịu trách nhiệm phát triển Backend & Frontend...,Có tối thiểu 1 năm kinh nghiệm phát triển Back...,"{'Cấp bậc': 'Nhân viên', 'Học vấn': 'Trung cấp...","[{'box_title': 'Danh mục Nghề liên quan', 'cat...","['.Net', 'Python', 'JavaScript', 'TypeScript',...","['.Net Framework', 'Python (Flask/Django)', 'R..."
3,3,4,"{'TECH_SKILL': ['Odoo', 'Python', 'PostgreSQL'...",4,Lập Trình Odoo ( Python ),"Phát triển, tùy biến các module trên nền tảng ...",Nam/Nữ - Từ 23 tuổi trở lên Tốt nghiệp Đại học...,"{'Cấp bậc': 'Trưởng nhóm', 'Học vấn': 'Cao Đẳn...","[{'box_title': 'Danh mục Nghề liên quan', 'cat...","['Odoo', 'Python', 'PostgreSQL', 'XML', 'JavaS...","['ERP', 'Sales', 'Purchase', 'Inventory', 'Acc..."
4,4,6,"{'TECH_SKILL': ['Django', 'MySQL', 'PostgreSQL...",6,Python Developer,Tham gia dự án với vai trò Python Developer và...,Kinh nghiệm làm việc từ 2 năm trở lên ở vị trí...,"{'Cấp bậc': 'Trưởng nhóm', 'Học vấn': 'Đại Học...","[{'box_title': 'Danh mục Nghề liên quan', 'cat...","['Django', 'MySQL', 'PostgreSQL']","['OOP', 'Web Development', 'DBMS', 'ORM', 'Des..."
...,...,...,...,...,...,...,...,...,...,...,...
880,880,940,"{'TECH_SKILL': ['QC/QA', 'Kiểm soát chất lượng...",940,Kiểm Soát Chất Lượng - Qa/Qc Gia Dụng,"- Kiểm tra chất lượng nguyên vật liệu đầu vào,...","- Nam, sức khỏe tốt - Có kinh nghiệm từ 1 năm ...","{'Cấp bậc': 'Nhân viên', 'Học vấn': 'Trung cấp...","[{'box_title': 'Danh mục Nghề liên quan', 'cat...","['QC/QA', 'Kiểm soát chất lượng']","['Tiêu chuẩn kiểm định chất lượng sản phẩm', '..."
881,881,941,{'TECH_SKILL': ['Kỹ năng về kiểm soát chất lượ...,941,Chuyên Viên Vệ Sinh An Toàn Thực Phẩm ( QA ),- Đảm bảo vệ sinh an toàn thực phẩm (VSATTP) t...,"- Có kinh nghiệm về kiểm soát chất lượng, ưu t...","{'Cấp bậc': 'Nhân viên', 'Học vấn': 'Cao Đẳng ...","[{'box_title': 'Danh mục Nghề liên quan', 'cat...","['Kỹ năng về kiểm soát chất lượng, an toàn thự...",['Kiến thức về VSATTP (Vệ sinh An Toàn Thực Ph...
882,882,942,"{'TECH_SKILL': ['Google Suite', 'Canva', 'Powe...",942,Chuyên Viên Phát Triển Chương Trình Và Học Liệu,1. Phát triển chương trình & học liệu (80%)/ C...,1.Trình độ chuyên môn/ Professional Qualificat...,"{'Cấp bậc': 'Nhân viên', 'Học vấn': 'Đại Học t...","[{'box_title': 'Danh mục Nghề liên quan', 'cat...","['Google Suite', 'Canva', 'PowerPoint', 'ChatG...","['Pedagogical thinking', 'Program logic', 'Lea..."
883,883,996,"{'TECH_SKILL': ['8D', 'FMEA', '5 Core Tools'],...",996,Kỹ Sư Chất Lượng ( Tiếng Trung ),Chịu trách nhiệm kiểm tra chất lượng trong quá...,Có kinh nghiệm làm việc ở vị trí Quản lý chất ...,"{'Cấp bậc': 'Nhân viên', 'Học vấn': 'Trung cấp...","[{'box_title': 'Danh mục Nghề liên quan', 'cat...","['8D', 'FMEA', '5 Core Tools']","['Quality Management Systems', 'Customer Relat..."
884,884,943,"{'TECH_SKILL': ['ISO', 'HACCP'], 'KNOWLEDGE': ...",943,Nhân Viên Quản Lý Chất Lượng ( QC ),"- Kiểm tra, giám sát, quản lý chất lượng của h...","- Tốt nghiệp Đại học chuyên ngành thủy sản, th...","{'Cấp bậc': 'Nhân viên', 'Học vấn': 'Đại Học t...","[{'box_title': 'Danh mục Nghề liên quan', 'cat...","['ISO', 'HACCP']","['Chất lượng hệ thống', 'An toàn thực phẩm']"

In [ ]:
mota_df = process_merged_df[["job_id", "desc_mota","TECH_SKILL" , "KNOWLEDGE"]].copy().rename({
    "desc_mota": "doc"
}, axis=1)
mota_df

,job_id,doc,TECH_SKILL,KNOWLEDGE
0,1,"Tham gia phát triển, xây dựng và duy trì hệ th...","['Python', 'Microservices', 'Docker', 'Kuberne...",['Frontend (ReactJS)']
1,2,Role Overview We are seeking a motivated and d...,"['Python', 'SQL', 'Pandas', 'NumPy', 'Backtrad...","['Quantitative Trading', 'Financial Markets', ..."
2,3,Chịu trách nhiệm phát triển Backend & Frontend...,"['.Net', 'Python', 'JavaScript', 'TypeScript',...","['.Net Framework', 'Python (Flask/Django)', 'R..."
3,4,"Phát triển, tùy biến các module trên nền tảng ...","['Odoo', 'Python', 'PostgreSQL', 'XML', 'JavaS...","['ERP', 'Sales', 'Purchase', 'Inventory', 'Acc..."
4,6,Tham gia dự án với vai trò Python Developer và...,"['Django', 'MySQL', 'PostgreSQL']","['OOP', 'Web Development', 'DBMS', 'ORM', 'Des..."
...,...,...,...,...
880,940,"- Kiểm tra chất lượng nguyên vật liệu đầu vào,...","['QC/QA', 'Kiểm soát chất lượng']","['Tiêu chuẩn kiểm định chất lượng sản phẩm', '..."
881,941,- Đảm bảo vệ sinh an toàn thực phẩm (VSATTP) t...,"['Kỹ năng về kiểm soát chất lượng, an toàn thự...",['Kiến thức về VSATTP (Vệ sinh An Toàn Thực Ph...
882,942,1. Phát triển chương trình & học liệu (80%)/ C...,"['Google Suite', 'Canva', 'PowerPoint', 'ChatG...","['Pedagogical thinking', 'Program logic', 'Lea..."
883,996,Chịu trách nhiệm kiểm tra chất lượng trong quá...,"['8D', 'FMEA', '5 Core Tools']","['Quality Management Systems', 'Customer Relat..."
884,943,"- Kiểm tra, giám sát, quản lý chất lượng của h...","['ISO', 'HACCP']","['Chất lượng hệ thống', 'An toàn thực phẩm']"

In [ ]:
yeucau_df = process_merged_df[["job_id", "desc_yeucau","TECH_SKILL" , "KNOWLEDGE"]].copy().rename({
    "desc_yeucau": "doc"
}, axis=1)
yeucau_df

,job_id,doc,TECH_SKILL,KNOWLEDGE
0,1,"Cử nhân chuyên ngành Công nghệ thông tin, Điện...","['Python', 'Microservices', 'Docker', 'Kuberne...",['Frontend (ReactJS)']
1,2,Must-haves Senior student or graduated with a ...,"['Python', 'SQL', 'Pandas', 'NumPy', 'Backtrad...","['Quantitative Trading', 'Financial Markets', ..."
2,3,Có tối thiểu 1 năm kinh nghiệm phát triển Back...,"['.Net', 'Python', 'JavaScript', 'TypeScript',...","['.Net Framework', 'Python (Flask/Django)', 'R..."
3,4,Nam/Nữ - Từ 23 tuổi trở lên Tốt nghiệp Đại học...,"['Odoo', 'Python', 'PostgreSQL', 'XML', 'JavaS...","['ERP', 'Sales', 'Purchase', 'Inventory', 'Acc..."
4,6,Kinh nghiệm làm việc từ 2 năm trở lên ở vị trí...,"['Django', 'MySQL', 'PostgreSQL']","['OOP', 'Web Development', 'DBMS', 'ORM', 'Des..."
...,...,...,...,...
880,940,"- Nam, sức khỏe tốt - Có kinh nghiệm từ 1 năm ...","['QC/QA', 'Kiểm soát chất lượng']","['Tiêu chuẩn kiểm định chất lượng sản phẩm', '..."
881,941,"- Có kinh nghiệm về kiểm soát chất lượng, ưu t...","['Kỹ năng về kiểm soát chất lượng, an toàn thự...",['Kiến thức về VSATTP (Vệ sinh An Toàn Thực Ph...
882,942,1.Trình độ chuyên môn/ Professional Qualificat...,"['Google Suite', 'Canva', 'PowerPoint', 'ChatG...","['Pedagogical thinking', 'Program logic', 'Lea..."
883,996,Có kinh nghiệm làm việc ở vị trí Quản lý chất ...,"['8D', 'FMEA', '5 Core Tools']","['Quality Management Systems', 'Customer Relat..."
884,943,"- Tốt nghiệp Đại học chuyên ngành thủy sản, th...","['ISO', 'HACCP']","['Chất lượng hệ thống', 'An toàn thực phẩm']"

In [ ]:
train_df = pd.concat([mota_df, yeucau_df], axis=0).reset_index(drop=True)
display(train_df)

,job_id,doc,TECH_SKILL,KNOWLEDGE
0,1,"Tham gia phát triển, xây dựng và duy trì hệ th...","['Python', 'Microservices', 'Docker', 'Kuberne...",['Frontend (ReactJS)']
1,2,Role Overview We are seeking a motivated and d...,"['Python', 'SQL', 'Pandas', 'NumPy', 'Backtrad...","['Quantitative Trading', 'Financial Markets', ..."
2,3,Chịu trách nhiệm phát triển Backend & Frontend...,"['.Net', 'Python', 'JavaScript', 'TypeScript',...","['.Net Framework', 'Python (Flask/Django)', 'R..."
3,4,"Phát triển, tùy biến các module trên nền tảng ...","['Odoo', 'Python', 'PostgreSQL', 'XML', 'JavaS...","['ERP', 'Sales', 'Purchase', 'Inventory', 'Acc..."
4,6,Tham gia dự án với vai trò Python Developer và...,"['Django', 'MySQL', 'PostgreSQL']","['OOP', 'Web Development', 'DBMS', 'ORM', 'Des..."
...,...,...,...,...
1765,940,"- Nam, sức khỏe tốt - Có kinh nghiệm từ 1 năm ...","['QC/QA', 'Kiểm soát chất lượng']","['Tiêu chuẩn kiểm định chất lượng sản phẩm', '..."
1766,941,"- Có kinh nghiệm về kiểm soát chất lượng, ưu t...","['Kỹ năng về kiểm soát chất lượng, an toàn thự...",['Kiến thức về VSATTP (Vệ sinh An Toàn Thực Ph...
1767,942,1.Trình độ chuyên môn/ Professional Qualificat...,"['Google Suite', 'Canva', 'PowerPoint', 'ChatG...","['Pedagogical thinking', 'Program logic', 'Lea..."
1768,996,Có kinh nghiệm làm việc ở vị trí Quản lý chất ...,"['8D', 'FMEA', '5 Core Tools']","['Quality Management Systems', 'Customer Relat..."
1769,943,"- Tốt nghiệp Đại học chuyên ngành thủy sản, th...","['ISO', 'HACCP']","['Chất lượng hệ thống', 'An toàn thực phẩm']"

In [ ]:
import re
tokens = re.findall(r'\w+|[^\w\s]', str("Phát triển và bảo trì các hệ thống backend sử dụng Python/Django. Xây dựng và tối ưu RESTful API phục vụ cho ứng dụng web và mobile. Phối hợp chặt chẽ với Product Manager và team Frontend trong việc phân tích, thiết kế và triển khai tính năng mới. Viết code sạch, dễ bảo trì, có test đầy đủ theo best practices. Đảm bảo hiệu năng, khả năng mở rộng và bảo mật của hệ thống. Review code, hướng dẫn các thành viên junior và đóng góp cải tiến quy trình làm việc của team. Giao tiếp hiệu quả với các team liên chức năng và khách hàng quốc tế."))
print(tokens)

['Phát', 'triển', 'và', 'bảo', 'trì', 'các', 'hệ', 'thống', 'backend', 'sử', 'dụng', 'Python', '/', 'Django', '.', 'Xây', 'dựng', 'và', 'tối', 'ưu', 'RESTful', 'API', 'phục', 'vụ', 'cho', 'ứng', 'dụng', 'web', 'và', 'mobile', '.', 'Phối', 'hợp', 'chặt', 'chẽ', 'với', 'Product', 'Manager', 'và', 'team', 'Frontend', 'trong', 'việc', 'phân', 'tích', ',', 'thiết', 'kế', 'và', 'triển', 'khai', 'tính', 'năng', 'mới', '.', 'Viết', 'code', 'sạch', ',', 'dễ', 'bảo', 'trì', ',', 'có', 'test', 'đầy', 'đủ', 'theo', 'best', 'practices', '.', 'Đảm', 'bảo', 'hiệu', 'năng', ',', 'khả', 'năng', 'mở', 'rộng', 'và', 'bảo', 'mật', 'của', 'hệ', 'thống', '.', 'Review', 'code', ',', 'hướng', 'dẫn', 'các', 'thành', 'viên', 'junior', 'và', 'đóng', 'góp', 'cải', 'tiến', 'quy', 'trình', 'làm', 'việc', 'của', 'team', '.', 'Giao', 'tiếp', 'hiệu', 'quả', 'với', 'các', 'team', 'liên', 'chức', 'năng', 'và', 'khách', 'hàng', 'quốc', 'tế', '.']

In [ ]:
label_names = ["O", "B-TECH_SKILL", "I-TECH_SKILL", "B-KNOW", "I-KNOW"]
id2label = {i: label for i, label in enumerate(label_names)}
label2id = {label: i for i, label in enumerate(label_names)}

assert all(label == label.strip() for label in label_names), label_names
print(label_names)

In [ ]:
import ast
import re
import unicodedata
from collections import Counter

import pandas as pd

TOKEN_PATTERN = re.compile(r"\w+|[^\w\s]", flags=re.UNICODE)


def normalize_text(value):
    """Normalize text before token matching so labels are less noisy."""
    value = unicodedata.normalize("NFC", str(value)).strip().lower()
    value = re.sub(r"\s+", " ", value)
    return value


def tokenize_text(value):
    return TOKEN_PATTERN.findall(unicodedata.normalize("NFC", str(value)))


def ensure_list(data):
    if isinstance(data, list):
        return data
    if data is None or pd.isna(data):
        return []
    if isinstance(data, str):
        try:
            parsed = ast.literal_eval(data)
            return parsed if isinstance(parsed, list) else []
        except (SyntaxError, ValueError):
            return []
    return []


def convert_to_bio_format(text, tech_skill, knowledge):
    tokens = tokenize_text(text)
    normalized_tokens = [normalize_text(token) for token in tokens]
    labels = [label2id["O"]] * len(tokens)
    conflicts = []

    keyword_specs = []
    for entity_type, keywords in [
        ("TECH_SKILL", ensure_list(tech_skill)),
        ("KNOW", ensure_list(knowledge)),
    ]:
        for keyword in keywords:
            keyword_tokens = tokenize_text(keyword)
            normalized_keyword_tokens = [normalize_text(token) for token in keyword_tokens]
            normalized_keyword_tokens = [token for token in normalized_keyword_tokens if token]
            if normalized_keyword_tokens:
                keyword_specs.append((
                    len(normalized_keyword_tokens),
                    entity_type,
                    str(keyword),
                    normalized_keyword_tokens,
                ))

    # Longest phrases first prevents short keywords like "Java" from stealing
    # tokens inside longer entities like "Java Script" when both exist.
    keyword_specs.sort(key=lambda item: item[0], reverse=True)

    for keyword_len, entity_type, keyword, keyword_tokens in keyword_specs:
        b_tag = label2id[f"B-{entity_type}"]
        i_tag = label2id[f"I-{entity_type}"]

        for start in range(0, len(tokens) - keyword_len + 1):
            end = start + keyword_len
            if normalized_tokens[start:end] != keyword_tokens:
                continue

            existing = labels[start:end]
            if any(label != label2id["O"] for label in existing):
                existing_names = [id2label[label] for label in existing]
                target_names = [id2label[b_tag]] + [id2label[i_tag]] * (keyword_len - 1)
                if existing_names != target_names:
                    conflicts.append({
                        "keyword": keyword,
                        "entity_type": entity_type,
                        "span": (start, end),
                        "tokens": tokens[start:end],
                        "existing_labels": existing_names,
                        "target_labels": target_names,
                    })
                continue

            labels[start] = b_tag
            for pos in range(start + 1, end):
                labels[pos] = i_tag

    return {"tokens": tokens, "ner_tags": labels, "conflicts": conflicts}


def validate_bio_sequence(label_ids):
    previous_entity = None
    for label_id in label_ids:
        label = id2label[label_id]
        if label == "O":
            previous_entity = None
            continue
        prefix, entity = label.split("-", 1)
        if prefix == "B":
            previous_entity = entity
            continue
        if prefix == "I" and previous_entity == entity:
            continue
        return False
    return True


def summarize_bio_quality(df):
    conflict_count = sum(len(item.get("conflicts", [])) for item in df["parse_bio"])
    invalid_count = sum(not validate_bio_sequence(item["ner_tags"]) for item in df["parse_bio"])
    label_counter = Counter(
        id2label[label]
        for item in df["parse_bio"]
        for label in item["ner_tags"]
    )
    return {
        "rows": len(df),
        "conflicts": conflict_count,
        "invalid_bio_rows": invalid_count,
        "label_distribution": dict(label_counter),
    }

In [ ]:
import pprint


print(train_df.iloc[0]["doc"], train_df.iloc[0]["TECH_SKILL"], train_df.iloc[0]["KNOWLEDGE"])

# This should now work without the ValueError
pprint.pprint(convert_to_bio_format(
    train_df.iloc[0]["doc"],
    train_df.iloc[0]["TECH_SKILL"],
    train_df.iloc[0]["KNOWLEDGE"]
))

Tham gia phát triển, xây dựng và duy trì hệ thống backend bằng Python theo kiến trúc microservices. Thiết kế, triển khai và quản lý dịch vụ chạy trên Docker và Kubernetes (k8s). Tích hợp API, tối ưu hóa hiệu năng hệ thống và xử lý dữ liệu lớn. Phối hợp với nhóm phát triển sản phẩm để tích hợp các sản phẩm nền vào các ứng dụng thực tiễn dành cho bảo hiểm, tài chính,.... ['Python', 'Microservices', 'Docker', 'Kubernetes', 'RESTful API', 'SQL/NoSQL'] ['Frontend (ReactJS)']
{'ner_tags': [0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              1,
              0,
              0,
              0,
              1,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              1,
              0,
              1,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0,
              0],
 'tokens': ['Tham',
            'gia',
            'phát',
            'triển',
            ',',
            'xây',
            'dựng',
            'và',
            'duy',
            'trì',
            'hệ',
            'thống',
            'backend',
            'bằng',
            'Python',
            'theo',
            'kiến',
            'trúc',
            'microservices',
            '.',
            'Thiết',
            'kế',
            ',',
            'triển',
            'khai',
            'và',
            'quản',
            'lý',
            'dịch',
            'vụ',
            'chạy',
            'trên',
            'Docker',
            'và',
            'Kubernetes',
            '(',
            'k8s',
            ')',
            '.',
            'Tích',
            'hợp',
            'API',
            ',',
            'tối',
            'ưu',
            'hóa',
            'hiệu',
            'năng',
            'hệ',
            'thống',
            'và',
            'xử',
            'lý',
            'dữ',
            'liệu',
            'lớn',
            '.',
            'Phối',
            'hợp',
            'với',
            'nhóm',
            'phát',
            'triển',
            'sản',
            'phẩm',
            'để',
            'tích',
            'hợp',
            'các',
            'sản',
            'phẩm',
            'nền',
            'vào',
            'các',
            'ứng',
            'dụng',
            'thực',
            'tiễn',
            'dành',
            'cho',
            'bảo',
            'hiểm',
            ',',
            'tài',
            'chính',
            ',',
            '.',
            '.',
            '.',
            '.']}

In [ ]:
train_df["parse_bio"] = train_df.apply(
    lambda row: convert_to_bio_format(row["doc"], row["TECH_SKILL"], row["KNOWLEDGE"]),
    axis=1,
)

bio_quality = summarize_bio_quality(train_df)
print(bio_quality)

In [ ]:
train_df

,job_id,doc,TECH_SKILL,KNOWLEDGE,parse_bio
0,1,"Tham gia phát triển, xây dựng và duy trì hệ th...","['Python', 'Microservices', 'Docker', 'Kuberne...",['Frontend (ReactJS)'],"{'tokens': ['Tham', 'gia', 'phát', 'triển', ',..."
1,2,Role Overview We are seeking a motivated and d...,"['Python', 'SQL', 'Pandas', 'NumPy', 'Backtrad...","['Quantitative Trading', 'Financial Markets', ...","{'tokens': ['Role', 'Overview', 'We', 'are', '..."
2,3,Chịu trách nhiệm phát triển Backend & Frontend...,"['.Net', 'Python', 'JavaScript', 'TypeScript',...","['.Net Framework', 'Python (Flask/Django)', 'R...","{'tokens': ['Chịu', 'trách', 'nhiệm', 'phát', ..."
3,4,"Phát triển, tùy biến các module trên nền tảng ...","['Odoo', 'Python', 'PostgreSQL', 'XML', 'JavaS...","['ERP', 'Sales', 'Purchase', 'Inventory', 'Acc...","{'tokens': ['Phát', 'triển', ',', 'tùy', 'biến..."
4,6,Tham gia dự án với vai trò Python Developer và...,"['Django', 'MySQL', 'PostgreSQL']","['OOP', 'Web Development', 'DBMS', 'ORM', 'Des...","{'tokens': ['Tham', 'gia', 'dự', 'án', 'với', ..."
...,...,...,...,...,...
1765,940,"- Nam, sức khỏe tốt - Có kinh nghiệm từ 1 năm ...","['QC/QA', 'Kiểm soát chất lượng']","['Tiêu chuẩn kiểm định chất lượng sản phẩm', '...","{'tokens': ['-', 'Nam', ',', 'sức', 'khỏe', 't..."
1766,941,"- Có kinh nghiệm về kiểm soát chất lượng, ưu t...","['Kỹ năng về kiểm soát chất lượng, an toàn thự...",['Kiến thức về VSATTP (Vệ sinh An Toàn Thực Ph...,"{'tokens': ['-', 'Có', 'kinh', 'nghiệm', 'về',..."
1767,942,1.Trình độ chuyên môn/ Professional Qualificat...,"['Google Suite', 'Canva', 'PowerPoint', 'ChatG...","['Pedagogical thinking', 'Program logic', 'Lea...","{'tokens': ['1', '.', 'Trình', 'độ', 'chuyên',..."
1768,996,Có kinh nghiệm làm việc ở vị trí Quản lý chất ...,"['8D', 'FMEA', '5 Core Tools']","['Quality Management Systems', 'Customer Relat...","{'tokens': ['Có', 'kinh', 'nghiệm', 'làm', 'vi..."
1769,943,"- Tốt nghiệp Đại học chuyên ngành thủy sản, th...","['ISO', 'HACCP']","['Chất lượng hệ thống', 'An toàn thực phẩm']","{'tokens': ['-', 'Tốt', 'nghiệp', 'Đại', 'học'..."

In [ ]:
checkpoint = "xlm-roberta-base"
# To compare Vietnamese-focused baselines later, rerun the notebook with:
# checkpoint = "vinai/phobert-base"

label_names = ["O", "B-TECH_SKILL", "I-TECH_SKILL", "B-KNOW", "I-KNOW"]
id2label = {i: label for i, label in enumerate(label_names)}
label2id = {label: i for i, label in enumerate(label_names)}

assert all(label == label.strip() for label in label_names), label_names

In [ ]:
print(id2label)
print(label2id)

{0: 'O', 1: 'B-TECH_SKILL', 2: 'I-TECH_SKILL ', 3: 'B-KNOW', 4: 'I-KNOW'}
{'O': 0, 'B-TECH_SKILL': 1, 'I-TECH_SKILL ': 2, 'B-KNOW': 3, 'I-KNOW': 4}

In [ ]:
from transformers import AutoTokenizer

# Create a tokenizer instance by loading the pre-trained checkpoint.
tokenizer = AutoTokenizer.from_pretrained(checkpoint)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/615 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

In [ ]:
print(train_df.iloc[1]["parse_bio"]["tokens"])

['Role', 'Overview', 'We', 'are', 'seeking', 'a', 'motivated', 'and', 'detail', '-', 'oriented', 'Quantitative', 'Trading', 'Intern', 'to', 'join', 'our', 'Equity', 'Derivatives', 'Trading', 'Desk', '.', 'The', 'intern', 'will', 'support', 'the', 'quantitative', 'trading', 'team', 'in', 'researching', ',', 'backtesting', ',', 'and', 'analyzing', 'trading', 'strategies', ',', 'working', 'closely', 'with', 'quant', 'researchers', 'and', 'traders', '.', 'This', 'role', 'offers', 'hands', '-', 'on', 'exposure', 'to', 'quantitative', 'trading', 'workflows', 'using', 'real', 'market', 'data', '.', 'Key', 'Responsibilities', 'Data', 'Preparation', '&', 'Analysis', 'Support', 'the', 'extraction', ',', 'cleaning', ',', 'and', 'preparation', 'of', 'time', '-', 'series', 'financial', 'data', '(', 'stocks', ',', 'futures', ',', 'warrants', ')', 'using', 'SQL', 'and', 'Python', '.', 'Assist', 'in', 'ensuring', 'data', 'quality', 'for', 'backtesting', ',', 'including', 'handling', 'missing', 'values', 'and', 'basic', 'data', 'inconsistencies', '.', 'Backtesting', '&', 'Strategy', 'Support', 'Assist', 'in', 'implementing', 'and', 'testing', 'quantitative', 'trading', 'strategies', '(', 'e', '.', 'g', '.', 'momentum', ',', 'mean', '-', 'reversion', ',', 'trend', '-', 'following', ')', 'using', 'Python', '.', 'Run', 'backtesting', 'simulations', 'and', 'help', 'evaluate', 'strategy', 'behavior', 'across', 'different', 'market', 'conditions', '.', 'Performance', 'Evaluation', '&', 'Documentation', 'Analyze', 'key', 'performance', 'metrics', '(', 'e', '.', 'g', '.', 'return', ',', 'volatility', ',', 'drawdown', ',', 'risk', '-', 'adjusted', 'performance', ')', '.', 'Summarize', 'backtesting', 'results', 'and', 'observations', 'in', 'clear', 'reports', 'to', 'support', 'discussions', 'with', 'senior', 'quants', 'and', 'traders', '.', 'Model', 'Validation', 'Support', 'Assist', 'with', 'basic', 'robustness', 'checks', 'and', 'parameter', 'sensitivity', 'analysis', 'under', 'guidance', 'from', 'the', 'quant', 'team', '.']

In [ ]:
# Tokenize the first training example from the dataset
token = tokenizer(train_df.iloc[1]["parse_bio"]["tokens"],
                  truncation=True,
                  max_length=512,
                  stride=100,                            # Số token overlap là 100
                  return_overflowing_tokens=True,       # Bật tính năng chia nhỏ
                  is_split_into_words=True
)

# Print the tokenizer object, the tokenized tokens, and the word IDs
print(token, '\n--------------------------------------------------------------------------------------\n',
      token.tokens(),'\n--------------------------------------------------------------------------------------\n',
      token.word_ids())

{'input_ids': [[0, 2777, 133, 9578, 22751, 1401, 621, 191618, 10, 167729, 297, 136, 22443, 20, 23509, 297, 75344, 913, 4935, 125362, 5337, 19, 47, 33284, 2446, 145666, 939, 1310, 3984, 42991, 125362, 262, 1042, 6, 5, 581, 38478, 1221, 8060, 70, 88779, 5844, 71702, 7175, 23, 25188, 214, 6, 4, 4420, 6954, 214, 6, 4, 136, 7968, 53, 35401, 71702, 50531, 7, 6, 4, 20697, 20903, 538, 678, 55230, 25188, 1314, 136, 188535, 7, 6, 5, 3293, 31486, 64600, 44540, 20, 98, 197826, 47, 88779, 5844, 71702, 4488, 118664, 7, 17368, 2773, 16839, 2053, 6, 5, 26824, 6, 94399, 36584, 2449, 11809, 116548, 1363, 619, 114837, 164, 58832, 70, 4173, 10763, 6, 4, 174033, 6, 4, 136, 212485, 111, 1733, 20, 36549, 53477, 2053, 15, 31837, 7, 6, 4, 22690, 7, 6, 4, 183594, 7, 1388, 17368, 80866, 136, 145581, 6, 5, 54360, 23, 22, 7, 53089, 2053, 31897, 100, 4420, 6954, 214, 6, 4, 26719, 45064, 132283, 142424, 136, 62822, 2053, 23, 25553, 6892, 58732, 6, 5, 26828, 6954, 214, 619, 7832, 67, 3432, 58832, 54360, 23, 29479, 214, 136, 134234, 88779, 5844, 71702, 50531, 7, 15, 28, 6, 5, 706, 6, 5, 3095, 316, 6, 4, 29459, 20, 456, 46354, 6, 4, 12768, 20, 25632, 1388, 17368, 145581, 6, 5, 28398, 4420, 6954, 214, 40226, 5256, 136, 4358, 151575, 13, 113857, 123166, 36880, 12921, 16839, 27289, 6, 5, 94030, 151228, 1363, 619, 43101, 2320, 33326, 53, 731, 22799, 23718, 27079, 4439, 15, 28, 6, 5, 706, 6, 5, 30646, 6, 4, 174048, 2481, 6, 4, 79442, 34695, 6, 4, 10512, 20, 126596, 297, 23718, 1388, 6, 5, 131150, 14096, 13, 4420, 6954, 214, 50339, 136, 150556, 7, 23, 34735, 117729, 47, 8060, 35107, 7, 678, 22962, 55230, 7, 136, 188535, 7, 6, 5, 13293, 25447, 85, 1363, 58832, 54360, 678, 62822, 60627, 7432, 12765, 7, 136, 171859, 6, 176302, 2481, 114137, 1379, 196219, 1295, 70, 55230, 7175, 6, 5, 2]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], 'overflow_to_sample_mapping': [0]}
--------------------------------------------------------------------------------------
 ['<s>', '▁Ro', 'le', '▁Over', 'view', '▁We', '▁are', '▁seeking', '▁a', '▁motivat', 'ed', '▁and', '▁detail', '▁-', '▁orient', 'ed', '▁Quant', 'ita', 'tive', '▁Trading', '▁Inter', 'n', '▁to', '▁join', '▁our', '▁Equi', 'ty', '▁Der', 'iva', 'tives', '▁Trading', '▁De', 'sk', '▁', '.', '▁The', '▁intern', '▁will', '▁support', '▁the', '▁quantitat', 'ive', '▁trading', '▁team', '▁in', '▁research', 'ing', '▁', ',', '▁back', 'test', 'ing', '▁', ',', '▁and', '▁anal', 'y', 'zing', '▁trading', '▁strategie', 's', '▁', ',', '▁working', '▁close', 'ly', '▁with', '▁quant', '▁research', 'ers', '▁and', '▁trader', 's', '▁', '.', '▁This', '▁role', '▁offers', '▁hands', '▁-', '▁on', '▁exposure', '▁to', '▁quantitat', 'ive', '▁trading', '▁work', 'flow', 's', '▁using', '▁real', '▁market', '▁data', '▁', '.', '▁Key', '▁', 'Respons', 'ibili', 'ties', '▁Data', '▁Prepara', 'tion', '▁&', '▁Analys', 'is', '▁Support', '▁the', '▁extra', 'ction', '▁', ',', '▁cleaning', '▁', ',', '▁and', '▁preparation', '▁of', '▁time', '▁-', '▁series', '▁financial', '▁data', '▁(', '▁stock', 's', '▁', ',', '▁future', 's', '▁', ',', '▁warrant', 's', '▁)', '▁using', '▁SQL', '▁and', '▁Python', '▁', '.', '▁Assist', '▁in', '▁en', 's', 'uring', '▁data', '▁quality', '▁for', '▁back', 'test', 'ing', '▁', ',', '▁including', '▁handling', '▁missing', '▁values', '▁and', '▁basic', '▁data', '▁in', 'cons', 'isten', 'cies', '▁', '.', '▁Back', 'test', 'ing', '▁&', '▁Stra', 'te', 'gy', '▁Support', '▁Assist', '▁in', '▁implement', 'ing', '▁and', '▁testing', '▁quantitat', 'ive', '▁trading', '▁strategie', 's', '▁(', '▁e', '▁', '.', '▁g', '▁', '.', '▁moment', 'um', '▁', ',', '▁mean', '▁-', '▁re', 'version', '▁', ',', '▁trend', '▁-', '▁following', '▁)', '▁using', '▁Python', '▁', '.', '▁Run', '▁back', 'test', 'ing', '▁simula', 'tions', '▁and', '▁help', '▁evaluat', 'e', '▁strategy', '▁behavior', '▁across', '▁different', '▁market', '▁conditions', '▁', '.', '▁Performance', '▁Evalua', 'tion', '▁&', '▁Document', 'ation', '▁Anal', 'y', 'ze', '▁key', '▁performance', '▁metri', 'cs', '▁(', '▁e', '▁', '.', '▁g', '▁', '.', '▁return', '▁', ',', '▁volatil', 'ity', '▁', ',', '▁draw', 'down', '▁', ',', '▁risk', '▁-', '▁adjust', 'ed', '▁performance', '▁)', '▁', '.', '▁Summa', 'riz', 'e', '▁back', 'test', 'ing', '▁results', '▁and', '▁observation', 's', '▁in', '▁clear', '▁reports', '▁to', '▁support', '▁discussion', 's', '▁with', '▁senior', '▁quant', 's', '▁and', '▁trader', 's', '▁', '.', '▁Model', '▁Vali', 'da', 'tion', '▁Support', '▁Assist', '▁with', '▁basic', '▁robust', 'ness', '▁check', 's', '▁and', '▁parameter', '▁', 'sensitiv', 'ity', '▁analysis', '▁under', '▁guidance', '▁from', '▁the', '▁quant', '▁team', '▁', '.', '</s>']
--------------------------------------------------------------------------------------
 [None, 0, 0, 1, 1, 2, 3, 4, 5, 6, 6, 7, 8, 9, 10, 10, 11, 11, 11, 12, 13, 13, 14, 15, 16, 17, 17, 18, 18, 18, 19, 20, 20, 21, 21, 22, 23, 24, 25, 26, 27, 27, 28, 29, 30, 31, 31, 32, 32, 33, 33, 33, 34, 34, 35, 36, 36, 36, 37, 38, 38, 39, 39, 40, 41, 41, 42, 43, 44, 44, 45, 46, 46, 47, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 56, 57, 58, 58, 58, 59, 60, 61, 62, 63, 63, 64, 65, 65, 65, 65, 66, 67, 67, 68, 69, 69, 70, 71, 72, 72, 73, 73, 74, 75, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 85, 86, 86, 87, 87, 88, 88, 89, 89, 90, 91, 92, 93, 94, 95, 95, 96, 97, 98, 98, 98, 99, 100, 101, 102, 102, 102, 103, 103, 104, 105, 106, 107, 108, 109, 110, 111, 111, 111, 111, 112, 112, 113, 113, 113, 114, 115, 115, 115, 116, 117, 118, 119, 119, 120, 121, 122, 122, 123, 124, 124, 125, 126, 127, 127, 128, 129, 129, 130, 130, 131, 131, 132, 133, 134, 134, 135, 135, 136, 137, 138, 139, 140, 141, 142, 142, 143, 144, 144, 144, 145, 145, 146, 147, 148, 148, 149, 150, 151, 152, 153, 154, 155, 155, 156, 157, 157, 158, 159, 159, 160, 160, 160, 161, 162, 163, 163, 164, 165, 166, 166, 167, 168, 168, 169, 170, 170, 171, 171, 172, 172, 173, 173, 174, 174, 175, 176, 177, 177, 178, 179, 180, 180, 181, 181, 181, 182, 182, 182, 183, 184, 185, 185, 186, 187, 188, 189, 190, 191, 191, 192, 193, 194, 194, 195, 196, 196, 197, 197, 198, 199, 199, 199, 200, 201, 202, 203, 204, 204, 205, 205, 206, 207, 208, 208, 208, 209, 210, 211, 212, 213, 214, 215, 216, 216, None]

In [ ]:
print(f"Maximum number of tokens for {checkpoint}: {tokenizer.model_max_length}")

Maximum number of tokens for xlm-roberta-base: 512

In [ ]:
def align_target(labels, word_ids):
    begin2inside = {
        1: 2,  # B-LANG (1) -> I-LANG (2)
        3: 4   # B-TECH (3) -> I-TECH (4)
    }

    align_labels = []
    last_word = None

    for word in word_ids:
        if word is None:
            label = -100
        elif word != last_word:
            label = labels[word]
        else:
            label = labels[word]
            if label in begin2inside:
                label = begin2inside[label]

        align_labels.append(label)
        last_word = word

    return align_labels

In [ ]:
# Extract labels and word_ids
labels = train_df.iloc[1]["parse_bio"]['ner_tags']
word_ids = token.word_ids()

# Use the align_target function to align labels
aligned_target = align_target(labels, word_ids)

print("labels:\n")
print(labels)

print("words id:\n")
print(word_ids)
# Print tokenized tokens, original labels, and aligned labels
print(token.tokens(), '\n--------------------------------------------------------------------------------------\n',
      labels, '\n--------------------------------------------------------------------------------------\n',
      aligned_target)

labels:

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
words id:

[None, 0, 0, 1, 1, 2, 3, 4, 5, 6, 6, 7, 8, 9, 10, 10, 11, 11, 11, 12, 13, 13, 14, 15, 16, 17, 17, 18, 18, 18, 19, 20, 20, 21, 21, 22, 23, 24, 25, 26, 27, 27, 28, 29, 30, 31, 31, 32, 32, 33, 33, 33, 34, 34, 35, 36, 36, 36, 37, 38, 38, 39, 39, 40, 41, 41, 42, 43, 44, 44, 45, 46, 46, 47, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 56, 57, 58, 58, 58, 59, 60, 61, 62, 63, 63, 64, 65, 65, 65, 65, 66, 67, 67, 68, 69, 69, 70, 71, 72, 72, 73, 73, 74, 75, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 85, 86, 86, 87, 87, 88, 88, 89, 89, 90, 91, 92, 93, 94, 95, 95, 96, 97, 98, 98, 98, 99, 100, 101, 102, 102, 102, 103, 103, 104, 105, 106, 107, 108, 109, 110, 111, 111, 111, 111, 112, 112, 113, 113, 113, 114, 115, 115, 115, 116, 117, 118, 119, 119, 120, 121, 122, 122, 123, 124, 124, 125, 126, 127, 127, 128, 129, 129, 130, 130, 131, 131, 132, 133, 134, 134, 135, 135, 136, 137, 138, 139, 140, 141, 142, 142, 143, 144, 144, 144, 145, 145, 146, 147, 148, 148, 149, 150, 151, 152, 153, 154, 155, 155, 156, 157, 157, 158, 159, 159, 160, 160, 160, 161, 162, 163, 163, 164, 165, 166, 166, 167, 168, 168, 169, 170, 170, 171, 171, 172, 172, 173, 173, 174, 174, 175, 176, 177, 177, 178, 179, 180, 180, 181, 181, 181, 182, 182, 182, 183, 184, 185, 185, 186, 187, 188, 189, 190, 191, 191, 192, 193, 194, 194, 195, 196, 196, 197, 197, 198, 199, 199, 199, 200, 201, 202, 203, 204, 204, 205, 205, 206, 207, 208, 208, 208, 209, 210, 211, 212, 213, 214, 215, 216, 216, None]
['<s>', '▁Ro', 'le', '▁Over', 'view', '▁We', '▁are', '▁seeking', '▁a', '▁motivat', 'ed', '▁and', '▁detail', '▁-', '▁orient', 'ed', '▁Quant', 'ita', 'tive', '▁Trading', '▁Inter', 'n', '▁to', '▁join', '▁our', '▁Equi', 'ty', '▁Der', 'iva', 'tives', '▁Trading', '▁De', 'sk', '▁', '.', '▁The', '▁intern', '▁will', '▁support', '▁the', '▁quantitat', 'ive', '▁trading', '▁team', '▁in', '▁research', 'ing', '▁', ',', '▁back', 'test', 'ing', '▁', ',', '▁and', '▁anal', 'y', 'zing', '▁trading', '▁strategie', 's', '▁', ',', '▁working', '▁close', 'ly', '▁with', '▁quant', '▁research', 'ers', '▁and', '▁trader', 's', '▁', '.', '▁This', '▁role', '▁offers', '▁hands', '▁-', '▁on', '▁exposure', '▁to', '▁quantitat', 'ive', '▁trading', '▁work', 'flow', 's', '▁using', '▁real', '▁market', '▁data', '▁', '.', '▁Key', '▁', 'Respons', 'ibili', 'ties', '▁Data', '▁Prepara', 'tion', '▁&', '▁Analys', 'is', '▁Support', '▁the', '▁extra', 'ction', '▁', ',', '▁cleaning', '▁', ',', '▁and', '▁preparation', '▁of', '▁time', '▁-', '▁series', '▁financial', '▁data', '▁(', '▁stock', 's', '▁', ',', '▁future', 's', '▁', ',', '▁warrant', 's', '▁)', '▁using', '▁SQL', '▁and', '▁Python', '▁', '.', '▁Assist', '▁in', '▁en', 's', 'uring', '▁data', '▁quality', '▁for', '▁back', 'test', 'ing', '▁', ',', '▁including', '▁handling', '▁missing', '▁values', '▁and', '▁basic', '▁data', '▁in', 'cons', 'isten', 'cies', '▁', '.', '▁Back', 'test', 'ing', '▁&', '▁Stra', 'te', 'gy', '▁Support', '▁Assist', '▁in', '▁implement', 'ing', '▁and', '▁testing', '▁quantitat', 'ive', '▁trading', '▁strategie', 's', '▁(', '▁e', '▁', '.', '▁g', '▁', '.', '▁moment', 'um', '▁', ',', '▁mean', '▁-', '▁re', 'version', '▁', ',', '▁trend', '▁-', '▁following', '▁)', '▁using', '▁Python', '▁', '.', '▁Run', '▁back', 'test', 'ing', '▁simula', 'tions', '▁and', '▁help', '▁evaluat', 'e', '▁strategy', '▁behavior', '▁across', '▁different', '▁market', '▁conditions', '▁', '.', '▁Performance', '▁Evalua', 'tion', '▁&', '▁Document', 'ation', '▁Anal', 'y', 'ze', '▁key', '▁performance', '▁metri', 'cs', '▁(', '▁e', '▁', '.', '▁g', '▁', '.', '▁return', '▁', ',', '▁volatil', 'ity', '▁', ',', '▁draw', 'down', '▁', ',', '▁risk', '▁-', '▁adjust', 'ed', '▁performance', '▁)', '▁', '.', '▁Summa', 'riz', 'e', '▁back', 'test', 'ing', '▁results', '▁and', '▁observation', 's', '▁in', '▁clear', '▁reports', '▁to', '▁support', '▁discussion', 's', '▁with', '▁senior', '▁quant', 's', '▁and', '▁trader', 's', '▁', '.', '▁Model', '▁Vali', 'da', 'tion', '▁Support', '▁Assist', '▁with', '▁basic', '▁robust', 'ness', '▁check', 's', '▁and', '▁parameter', '▁', 'sensitiv', 'ity', '▁analysis', '▁under', '▁guidance', '▁from', '▁the', '▁quant', '▁team', '▁', '.', '</s>']
--------------------------------------------------------------------------------------
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
--------------------------------------------------------------------------------------
 [-100, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 4, 4, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 4, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 4, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 4, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -100]

In [ ]:
aligned_labels = [label_names[t] if t >= 0 else None for t in aligned_target]

# Loop through tokens and aligned labels and print them
for x, y in zip(token.tokens(), aligned_labels):
    print(f"{x}\t{y}")

<s>	None
▁Ro	O
le	O
▁Over	O
view	O
▁We	O
▁are	O
▁seeking	O
▁a	O
▁motivat	O
ed	O
▁and	O
▁detail	O
▁-	O
▁orient	O
ed	O
▁Quant	B-KNOW
ita	I-KNOW
tive	I-KNOW
▁Trading	I-KNOW
▁Inter	O
n	O
▁to	O
▁join	O
▁our	O
▁Equi	O
ty	O
▁Der	O
iva	O
tives	O
▁Trading	O
▁De	O
sk	O
▁	O
.	O
▁The	O
▁intern	O
▁will	O
▁support	O
▁the	O
▁quantitat	B-KNOW
ive	I-KNOW
▁trading	I-KNOW
▁team	O
▁in	O
▁research	O
ing	O
▁	O
,	O
▁back	O
test	O
ing	O
▁	O
,	O
▁and	O
▁anal	O
y	O
zing	O
▁trading	O
▁strategie	O
s	O
▁	O
,	O
▁working	O
▁close	O
ly	O
▁with	O
▁quant	O
▁research	O
ers	O
▁and	O
▁trader	O
s	O
▁	O
.	O
▁This	O
▁role	O
▁offers	O
▁hands	O
▁-	O
▁on	O
▁exposure	O
▁to	O
▁quantitat	B-KNOW
ive	I-KNOW
▁trading	I-KNOW
▁work	O
flow	O
s	O
▁using	O
▁real	O
▁market	O
▁data	O
▁	O
.	O
▁Key	O
▁	O
Respons	O
ibili	O
ties	O
▁Data	O
▁Prepara	O
tion	O
▁&	O
▁Analys	O
is	O
▁Support	O
▁the	O
▁extra	O
ction	O
▁	O
,	O
▁cleaning	O
▁	O
,	O
▁and	O
▁preparation	O
▁of	O
▁time	O
▁-	O
▁series	O
▁financial	O
▁data	O
▁(	O
▁stock	O
s	O
▁	O
,	O
▁future	O
s	O
▁	O
,	O
▁warrant	O
s	O
▁)	O
▁using	O
▁SQL	B-TECH_SKILL
▁and	O
▁Python	B-TECH_SKILL
▁	O
.	O
▁Assist	O
▁in	O
▁en	O
s	O
uring	O
▁data	O
▁quality	O
▁for	O
▁back	O
test	O
ing	O
▁	O
,	O
▁including	O
▁handling	O
▁missing	O
▁values	O
▁and	O
▁basic	O
▁data	O
▁in	O
cons	O
isten	O
cies	O
▁	O
.	O
▁Back	O
test	O
ing	O
▁&	O
▁Stra	O
te	O
gy	O
▁Support	O
▁Assist	O
▁in	O
▁implement	O
ing	O
▁and	O
▁testing	O
▁quantitat	B-KNOW
ive	I-KNOW
▁trading	I-KNOW
▁strategie	O
s	O
▁(	O
▁e	O
▁	O
.	O
▁g	O
▁	O
.	O
▁moment	O
um	O
▁	O
,	O
▁mean	O
▁-	O
▁re	O
version	O
▁	O
,	O
▁trend	O
▁-	O
▁following	O
▁)	O
▁using	O
▁Python	B-TECH_SKILL
▁	O
.	O
▁Run	O
▁back	O
test	O
ing	O
▁simula	O
tions	O
▁and	O
▁help	O
▁evaluat	O
e	O
▁strategy	O
▁behavior	O
▁across	O
▁different	O
▁market	O
▁conditions	O
▁	O
.	O
▁Performance	O
▁Evalua	O
tion	O
▁&	O
▁Document	O
ation	O
▁Anal	O
y	O
ze	O
▁key	O
▁performance	O
▁metri	O
cs	O
▁(	O
▁e	O
▁	O
.	O
▁g	O
▁	O
.	O
▁return	O
▁	O
,	O
▁volatil	O
ity	O
▁	O
,	O
▁draw	O
down	O
▁	O
,	O
▁risk	O
▁-	O
▁adjust	O
ed	O
▁performance	O
▁)	O
▁	O
.	O
▁Summa	O
riz	O
e	O
▁back	O
test	O
ing	O
▁results	O
▁and	O
▁observation	O
s	O
▁in	O
▁clear	O
▁reports	O
▁to	O
▁support	O
▁discussion	O
s	O
▁with	O
▁senior	O
▁quant	O
s	O
▁and	O
▁trader	O
s	O
▁	O
.	O
▁Model	O
▁Vali	O
da	O
tion	O
▁Support	O
▁Assist	O
▁with	O
▁basic	O
▁robust	O
ness	O
▁check	O
s	O
▁and	O
▁parameter	O
▁	O
sensitiv	O
ity	O
▁analysis	O
▁under	O
▁guidance	O
▁from	O
▁the	O
▁quant	O
▁team	O
▁	O
.	O
</s>	None

In [ ]:
print(word_ids)

[None, 0, 0, 1, 1, 2, 3, 4, 5, 6, 6, 7, 8, 9, 10, 10, 11, 11, 11, 12, 13, 13, 14, 15, 16, 17, 17, 18, 18, 18, 19, 20, 20, 21, 21, 22, 23, 24, 25, 26, 27, 27, 28, 29, 30, 31, 31, 32, 32, 33, 33, 33, 34, 34, 35, 36, 36, 36, 37, 38, 38, 39, 39, 40, 41, 41, 42, 43, 44, 44, 45, 46, 46, 47, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 56, 57, 58, 58, 58, 59, 60, 61, 62, 63, 63, 64, 65, 65, 65, 65, 66, 67, 67, 68, 69, 69, 70, 71, 72, 72, 73, 73, 74, 75, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 85, 86, 86, 87, 87, 88, 88, 89, 89, 90, 91, 92, 93, 94, 95, 95, 96, 97, 98, 98, 98, 99, 100, 101, 102, 102, 102, 103, 103, 104, 105, 106, 107, 108, 109, 110, 111, 111, 111, 111, 112, 112, 113, 113, 113, 114, 115, 115, 115, 116, 117, 118, 119, 119, 120, 121, 122, 122, 123, 124, 124, 125, 126, 127, 127, 128, 129, 129, 130, 130, 131, 131, 132, 133, 134, 134, 135, 135, 136, 137, 138, 139, 140, 141, 142, 142, 143, 144, 144, 144, 145, 145, 146, 147, 148, 148, 149, 150, 151, 152, 153, 154, 155, 155, 156, 157, 157, 158, 159, 159, 160, 160, 160, 161, 162, 163, 163, 164, 165, 166, 166, 167, 168, 168, 169, 170, 170, 171, 171, 172, 172, 173, 173, 174, 174, 175, 176, 177, 177, 178, 179, 180, 180, 181, 181, 181, 182, 182, 182, 183, 184, 185, 185, 186, 187, 188, 189, 190, 191, 191, 192, 193, 194, 194, 195, 196, 196, 197, 197, 198, 199, 199, 199, 200, 201, 202, 203, 204, 204, 205, 205, 206, 207, 208, 208, 208, 209, 210, 211, 212, 213, 214, 215, 216, 216, None]

In [ ]:
print(labels)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [ ]:
# Define fake input data
words = ['<s>', '▁Top', '▁3', '▁reasons', '▁to', '▁join', '▁us', '▁-', '▁Lương', '▁và', '▁chế', '▁độ', '▁hấp', '▁dẫn', '▁', ',', '▁linh', '▁hoạt', '▁', ',', '▁cạnh', '▁tranh', '▁-', '▁Cơ', '▁hội', '▁thăng', '▁tiến', '▁', ',', '▁phát', '▁triển', '▁trong', '▁công', '▁việc', '▁-', '▁Mô', 'i', '▁trường', '▁thân', '▁thiện', '▁', ',', '▁trẻ', '▁trung', '▁', ',', '▁sáng', '▁tạo', '▁Job', '▁description', '▁-', '▁Xây', '▁dư', '▁', '̣', '▁ng', '▁ca', '▁́', '▁c', '▁', 'ư', '▁́', '▁ng', '▁du', '▁', '̣', '▁ng', '▁Mobile', '▁Bank', 'ing', '▁liên', '▁quan', '▁đê', '▁́', '▁n', '▁ca', '▁́', '▁c', '▁ma', '▁', '̉', '▁ng', '▁ta', '▁', '̀', '▁i', '▁chi', '▁́', '▁nh', '▁', ',', '▁Ngân', '▁hàng', '▁', ',', '▁Viễn', '▁thông', '▁trên', '▁nền', '▁tảng', '▁', 'IOS', '▁-', '▁Xây', '▁dựng', '▁các', '▁ứng', '▁dụng', '▁liên', '▁quan', '▁đến', '▁các', '▁phần', '▁tiện', '▁ích', '▁E', 'commerce', '▁-', '▁Nghiên', '▁cư', '▁́', '▁u', '▁', ',', '▁ti', '▁', '̀', '▁m', '▁ki', 'ê', '▁́', '▁m', '▁gia', '▁', '̉', '▁i', '▁pha', '▁́', '▁p', '▁vê', '▁', '̀', '▁vi', 'ê', '▁', '̣', '▁c', '▁a', '▁́', '▁p', '▁du', '▁', '̣', '▁ng', '▁ca', '▁́', '▁c', '▁ti', '▁́', '▁nh', '▁năng', '▁cu', '▁', '̉', '▁a', '▁thi', 'ê', '▁́', '▁t', '▁bi', '▁', '̣', '▁di', '▁đô', '▁', '̣', '▁ng', '▁va', '▁', '̀', '▁o', '▁ma', '▁', '̉', '▁ng', '▁ta', '▁', '̀', '▁i', '▁chi', '▁́', '▁nh', '▁', ',', '▁Ngân', '▁hàng', '▁', ',', '▁Viễn', '▁thông', '▁', '.', '▁-', '▁Duy', '▁tri', '▁', '̀', '▁', ',', '▁hô', '▁', '̃', '▁trơ', '▁', '̣', '▁', ',', '▁nâng', '▁câ', '▁́', '▁p', '▁ca', '▁́', '▁c', '▁', 'ư', '▁́', '▁ng', '▁du', '▁', '̣', '▁ng', '▁di', '▁', '̣', '▁ch', '▁vu', '▁', '̣', '▁đa', '▁', '̃', '▁pha', '▁́', '▁t', '▁tri', 'ê', '▁', '̉', '▁n', '▁cu', '▁', '̉', '▁a', '▁Công', '▁ty', '▁-', '▁Phát', '▁triển', '▁mới', '▁', ',', '▁nâng', '▁cấp', '▁ứng', '▁dụng', '▁cho', '▁các', '▁ngân', '▁hàng', '▁trong', '▁giai', '▁đoạn', '▁sắp', '▁tới', '▁', '.', '▁Your', '▁skills', '▁and', '▁experience', '▁-', '▁T', 'ốt', '▁nghiệp', '▁Đại', '▁học', '▁/', '▁Cao', '▁đẳng', '▁các', '▁chuyên', '▁ngành', '▁Công', '▁nghệ', '▁thông', '▁tin', '▁', ',', '▁Công', '▁nghệ', '▁phần', '▁mềm', '▁', ',', '▁', '.', '▁', '.', '▁', '.', '▁', '.', '▁', '.', '▁hoặc', '▁Trường', '▁đào', '▁tạo', '▁lập', '▁trình', '▁viên', '▁Quốc', '▁Tế', '▁(', '▁NI', 'IT', '▁', ',', '▁Ap', 'tech', '▁)', '▁trở', '▁lên', '▁-', '▁Có', '▁từ', '▁6', '▁tháng', '▁kinh', '▁nghiệm', '▁trở', '▁lên', '▁-', '▁Hiểu', '▁biết', '▁về', '▁x', 'Code', '▁', ',', '▁Swift', '▁', ',', '▁có', '▁kinh', '▁nghiệm', '▁lập', '▁trình', '▁ứng', '▁dụng', '▁trên', '▁', 'IOS', '▁-', '▁Có', '▁hiểu', '▁biết', '▁về', '▁Real', 'm', '▁', ',', '▁giao', '▁tiếp', '▁client', '▁–', '▁server', '▁thông', '▁qua', '▁R', 'EST', '▁và', '▁J', 'SON', '▁-', '▁Có', '▁kiến', '▁thức', '▁về', '▁Object', 'ive', '▁–', '▁C', '▁là', '▁1', '▁lợi', '▁thế', '▁', ',', '▁chịu', '▁khó', '▁học', '▁hỏi', '▁', ',', '▁tìm', '▁hiểu', '▁kiến', '▁thức', '▁mới', '▁-', '▁Ưu', '▁tiên', '▁ứng', '▁viên', '▁có', '▁kinh', '▁nghiệm', '▁làm', '▁về', '▁lĩnh', '▁vực', '▁tài', '▁chính', '▁', ',', '▁ngân', '▁hàng', '▁Why', '▁you', "▁'", '▁', 'll', '▁love', '▁working', '▁here', '▁1', '▁', '.', '▁Chế', '▁độ', '▁lương', '▁&', '▁thưởng', '▁hấp', '▁dẫn', '▁:', '▁-', '▁M', 'ức', '▁lương', '▁thỏa', '▁thuận', '▁theo', '▁năng', '▁lực', '▁', ',', '▁đánh', '▁giá', '▁năng', '▁lực', '▁hàng', '▁năm', '▁-', '▁Chế', '▁độ', '▁thưởng', '▁phong', '▁phú', '▁và', '▁hấp', '▁dẫn', '▁(', '▁Theo', '▁quy', '▁định', '▁và', '▁chính', '▁sách', '▁công', '▁ty', '▁)', '▁-', '▁Hỗ', '▁trợ', '▁ăn', '▁sáng', '▁miễn', '▁phí', '▁-', '▁Hỗ', '▁trợ', '▁ăn', '▁trưa', '▁:', '▁50', '▁', '.', '▁000', 'đ', '▁/', '▁ngày', '▁-', '▁Hỗ', '▁trợ', '▁gửi', '▁xe', '▁', ',', '▁xăng', '▁xe', '▁', ',', '▁điện', '▁thoại', '▁(', '▁tùy', '▁vị', '▁trí', '▁)', '▁-', '▁Hỗ', '▁trợ', '▁trang', '▁điểm', '▁cho', '▁CB', 'NV', '▁nữ', '▁-', '▁Qu', 'à', '▁tặng', '▁các', '▁ngày', '▁lễ', '▁trong', '▁năm', '▁2', '▁', '.', '▁Bảo', '▁hiểm', '▁&', '▁chăm', '▁sóc', '▁sức', '▁khỏe', '▁toàn', '▁diện', '▁:', '▁-', '▁BH', 'XH', '▁', ',', '▁BH', 'YT', '▁', ',', '▁BH', 'TN', '▁theo', '▁pháp', '▁luật', '▁hiện', '▁hành', '▁-', '▁G', 'ói', '▁bảo', '▁hiểm', '▁sức', '▁khỏe', '▁cao', '▁cấp', '▁24', '▁/', '▁7', '▁mua', '▁cho', '▁nhân', '▁viên', '▁&', '▁người', '▁thân', '▁nhân', '▁viên', '▁-', '▁Khám', '▁sức', '▁khỏe', '▁định', '▁kỳ', '▁hàng', '▁năm', '▁3', '▁', '.', '▁Mô', 'i', '▁trường', '▁làm', '▁việc', '▁hiện', '▁đại', '▁:', '▁-', '▁Cung', '▁cấp', '▁máy', '▁tính', '▁&', '▁thiết', '▁bị', '▁làm', '▁việc', '▁hiện', '▁đại', '▁-', '▁Văn', '▁phòng', '▁làm', '▁việc', '▁hiện', '▁đại', '▁', ',', '▁thiết', '▁bị', '▁làm', '▁việc', '▁Hi', '▁-', '▁tech', '▁-', '▁Không', '▁gian', '▁ăn', '▁nhẹ', '▁miễn', '▁phí', '▁(', '▁nước', '▁uống', '▁', ',', '▁trà', '▁cafe', '▁', ',', '▁hoa', '▁quả', '▁', ',', '▁sữa', '▁chua', '▁)', '▁4', '▁', '.', '▁Phát', '▁triển', '▁nghề', '▁nghiệp', '▁:', '▁-', '▁Cơ', '▁hội', '▁tiếp', '▁cận', '▁với', '▁những', '▁công', '▁nghệ', '▁mới', '▁', ',', '▁những', '▁dự', '▁án', '▁quy', '▁mô', '▁lớn', '▁-', '▁Làm', '▁việc', '▁cùng', '▁đội', '▁ngũ', '▁hơn', '▁2000', '▁nhân', '▁sự', '▁tài', '▁năng', '▁', ',', '▁có', '▁chuyên', '▁môn', '▁giỏi', '▁', ',', '▁dày', '▁d', 'ặ', 'n', '▁kinh', '▁nghiệm', '▁', ',', '▁tư', '▁duy', '▁chia', '▁sẻ', '▁-', '▁Được', '▁tài', '▁trợ', '▁kinh', '▁phí', '▁tham', '▁gia', '▁các', '▁chương', '▁trình', '▁đào', '▁tạo', '▁nâng', '▁cao', '▁năng', '▁lực', '▁-', '▁Công', '▁ty', '▁thành', '▁lập', '▁gần', '▁20', '▁năm', '▁với', '▁các', '▁sản', '▁phẩm', '▁&', '▁dịch', '▁vụ', '▁đã', '▁được', '▁k', 'hẳng', '▁định', '▁vị', '▁thế', '▁trên', '▁thị', '▁trường', '▁5', '▁', '.', '▁Hoạt', '▁động', '▁ngoại', '▁khóa', '▁phong', '▁phú', '▁:', '▁-', '▁Văn', '▁hóa', '▁công', '▁ty', '▁đặc', '▁sắc', '▁với', '▁nhiều', '▁hoạt', '▁động', '▁đoàn', '▁thể', '▁được', '▁quan', '▁tâm', '▁đầu', '▁tư', '▁:', '▁Team', '▁building', '▁', ',', '▁Ngh', 'ỉ', '▁mát', '▁(', '▁trong', '▁nước', '▁và', '▁nước', '▁ngoài', '▁)', '▁', ',', '▁20', '▁/', '▁10', '▁', ',', '▁Year', '▁End', '▁Party', '▁', ',', '▁hoạt', '▁động', '▁thiện', '▁nguyện', '▁', ',', '▁', '…', '▁-', '▁Các', '▁câu', '▁lạc', '▁bộ', '▁:', '▁C', 'LB', '▁Cầu', '▁lông', '▁', ',', '▁C', 'LB', '▁Bó', 'ng', '▁đá', '▁', ',', '▁C', 'LB', '▁Yoga', '▁', ',', '▁C', 'LB', '▁Đ', 'iền', '▁kinh', '▁', ',', '▁C', 'LB', '▁B', 'ơ', 'i', '▁Chúng', '▁tôi', '▁sẽ', '▁liên', '▁hệ', '▁qua', '▁điện', '▁thoại', '▁với', '▁những', '▁CV', '▁phù', '▁hợp', '▁trong', '▁vòng', '▁7', '▁ngày', '▁làm', '▁việc', '▁kể', '▁từ', '▁ngày', '▁ứng', '▁tuyển', '▁', '.', '▁Lưu', '▁ý', '▁:', '▁Công', '▁ty', '▁đang', '▁tuyển', '▁tại', '▁2', '▁văn', '▁phòng', '▁Hà', '▁Nội', '▁và', '▁Tp', '▁', '.', '▁Hồ', '▁Chí', '▁Minh', '▁', ',', '▁ứng', '▁viên', '▁vui', '▁lòng', '▁ghi', '▁rõ', '▁địa', '▁chỉ', '▁trên', '▁CV', '▁', '.', '</s>']
word_ids = [None, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 13, 14, 15, 16, 16, 17, 18, 19, 20, 21, 22, 23, 24, 24, 25, 26, 27, 28, 29, 30, 31, 31, 32, 33, 34, 35, 35, 36, 37, 38, 38, 39, 40, 41, 42, 43, 44, 45, 46, 46, 47, 48, 49, 50, 51, 51, 52, 53, 54, 55, 55, 56, 57, 58, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 68, 69, 70, 71, 71, 72, 73, 74, 75, 76, 76, 77, 78, 79, 79, 80, 81, 82, 83, 84, 85, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 99, 100, 101, 102, 103, 104, 105, 105, 106, 107, 107, 108, 109, 109, 110, 111, 112, 113, 113, 114, 115, 116, 117, 118, 119, 119, 120, 120, 121, 121, 122, 123, 124, 125, 126, 127, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 137, 138, 139, 139, 140, 141, 142, 143, 143, 144, 145, 146, 146, 147, 148, 149, 149, 150, 151, 152, 152, 153, 154, 155, 155, 156, 157, 158, 159, 160, 160, 161, 162, 163, 163, 164, 165, 166, 166, 167, 168, 169, 170, 170, 171, 171, 172, 173, 173, 174, 175, 175, 176, 176, 177, 178, 179, 180, 181, 182, 183, 184, 184, 185, 186, 187, 188, 188, 189, 190, 191, 191, 192, 193, 194, 194, 195, 196, 196, 197, 198, 199, 200, 200, 201, 201, 202, 203, 204, 204, 205, 206, 207, 208, 209, 210, 211, 212, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 226, 227, 228, 229, 230, 231, 232, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 246, 247, 248, 249, 250, 251, 251, 252, 252, 253, 253, 254, 254, 255, 255, 256, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 267, 268, 268, 269, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 286, 287, 287, 288, 289, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 298, 299, 300, 301, 302, 303, 304, 304, 305, 305, 306, 307, 308, 309, 310, 311, 312, 313, 313, 314, 315, 315, 316, 317, 318, 319, 320, 321, 321, 322, 323, 324, 325, 326, 327, 328, 328, 329, 330, 331, 332, 333, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 353, 354, 355, 356, 357, 358, 359, 359, 360, 361, 362, 363, 364, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 374, 375, 376, 377, 378, 379, 380, 381, 381, 382, 383, 384, 385, 386, 387, 388, 389, 390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 419, 420, 421, 421, 422, 422, 423, 424, 425, 426, 427, 428, 429, 430, 430, 431, 432, 433, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442, 443, 444, 445, 446, 447, 447, 448, 449, 450, 450, 451, 452, 453, 454, 455, 456, 457, 458, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467, 468, 469, 470, 470, 471, 471, 472, 472, 473, 473, 474, 474, 475, 476, 477, 478, 479, 480, 481, 481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493, 494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506, 507, 508, 509, 509, 510, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 536, 537, 538, 539, 540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552, 553, 554, 554, 555, 556, 557, 557, 558, 559, 560, 560, 561, 562, 563, 564, 565, 565, 566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578, 579, 580, 581, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591, 592, 593, 594, 595, 596, 597, 598, 599, 600, 600, 601, 602, 603, 604, 605, 605, 606, 607, 607, 607, 608, 609, 610, 610, 611, 612, 613, 614, 615, 616, 617, 618, 619, 620, 621, 622, 623, 624, 625, 626, 627, 628, 629, 630, 631, 632, 633, 634, 635, 636, 637, 638, 639, 640, 641, 642, 643, 644, 645, 646, 647, 648, 649, 649, 650, 651, 652, 653, 654, 655, 656, 657, 657, 658, 659, 660, 661, 662, 663, 664, 665, 666, 667, 668, 669, 670, 671, 672, 673, 674, 675, 676, 677, 678, 679, 680, 681, 682, 683, 684, 685, 686, 686, 687, 687, 688, 689, 690, 691, 692, 693, 694, 695, 696, 696, 697, 698, 699, 700, 700, 701, 702, 703, 704, 704, 705, 706, 707, 708, 709, 709, 710, 710, 711, 712, 713, 714, 715, 716, 717, 717, 718, 719, 720, 720, 721, 721, 722, 722, 723, 724, 724, 725, 725, 726, 727, 727, 728, 728, 729, 729, 730, 731, 731, 732, 732, 733, 733, 733, 734, 735, 736, 737, 738, 739, 740, 741, 742, 743, 744, 745, 746, 747, 748, 749, 750, 751, 752, 753, 754, 755, 756, 757, 758, 758, 759, 760, 761, 762, 763, 764, 765, 766, 767, 768, 769, 770, 771, 772, 773, 774, 774, 775, 776, 777, 778, 778, 779, 780, 781, 782, 783, 784, 785, 786, 787, 788, 789, 789, None]
labels = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

# Use the align_target function to align labels
aligned_target = align_target(labels, word_ids)

# Create a list of aligned labels using label names
aligned_labels = [label_names[t] if t >= 0 else None for t in aligned_target]

# Loop through words and aligned labels and print them
for x, y in zip(words, aligned_labels):
    print(f"{x}\t{y}")

<s>	None
▁Top	O
▁3	O
▁reasons	O
▁to	O
▁join	O
▁us	O
▁-	O
▁Lương	O
▁và	O
▁chế	O
▁độ	O
▁hấp	O
▁dẫn	O
▁	O
,	O
▁linh	O
▁hoạt	O
▁	O
,	O
▁cạnh	O
▁tranh	O
▁-	O
▁Cơ	O
▁hội	O
▁thăng	O
▁tiến	O
▁	O
,	O
▁phát	O
▁triển	O
▁trong	O
▁công	O
▁việc	O
▁-	O
▁Mô	O
i	O
▁trường	O
▁thân	O
▁thiện	O
▁	O
,	O
▁trẻ	O
▁trung	O
▁	O
,	O
▁sáng	O
▁tạo	O
▁Job	O
▁description	O
▁-	O
▁Xây	O
▁dư	O
▁	O
̣	O
▁ng	O
▁ca	O
▁́	O
▁c	O
▁	O
ư	O
▁́	O
▁ng	O
▁du	O
▁	O
̣	O
▁ng	O
▁Mobile	O
▁Bank	O
ing	O
▁liên	O
▁quan	O
▁đê	O
▁́	O
▁n	O
▁ca	O
▁́	O
▁c	O
▁ma	O
▁	O
̉	O
▁ng	O
▁ta	O
▁	O
̀	O
▁i	O
▁chi	O
▁́	O
▁nh	O
▁	O
,	O
▁Ngân	O
▁hàng	O
▁	O
,	O
▁Viễn	O
▁thông	O
▁trên	O
▁nền	O
▁tảng	O
▁	O
IOS	O
▁-	O
▁Xây	O
▁dựng	O
▁các	O
▁ứng	O
▁dụng	O
▁liên	O
▁quan	O
▁đến	O
▁các	O
▁phần	O
▁tiện	O
▁ích	O
▁E	O
commerce	O
▁-	O
▁Nghiên	O
▁cư	O
▁́	O
▁u	O
▁	O
,	O
▁ti	O
▁	O
̀	O
▁m	O
▁ki	O
ê	O
▁́	O
▁m	O
▁gia	O
▁	O
̉	O
▁i	O
▁pha	O
▁́	O
▁p	O
▁vê	O
▁	O
̀	O
▁vi	O
ê	O
▁	O
̣	O
▁c	O
▁a	O
▁́	O
▁p	O
▁du	O
▁	O
̣	O
▁ng	O
▁ca	O
▁́	O
▁c	O
▁ti	O
▁́	O
▁nh	O
▁năng	O
▁cu	O
▁	O
̉	O
▁a	O
▁thi	O
ê	O
▁́	O
▁t	O
▁bi	O
▁	O
̣	O
▁di	O
▁đô	O
▁	O
̣	O
▁ng	O
▁va	O
▁	O
̀	O
▁o	O
▁ma	O
▁	O
̉	O
▁ng	O
▁ta	O
▁	O
̀	O
▁i	O
▁chi	O
▁́	O
▁nh	O
▁	O
,	O
▁Ngân	O
▁hàng	O
▁	O
,	O
▁Viễn	O
▁thông	O
▁	O
.	O
▁-	O
▁Duy	O
▁tri	O
▁	O
̀	O
▁	O
,	O
▁hô	O
▁	O
̃	O
▁trơ	O
▁	O
̣	O
▁	O
,	O
▁nâng	O
▁câ	O
▁́	O
▁p	O
▁ca	O
▁́	O
▁c	O
▁	O
ư	O
▁́	O
▁ng	O
▁du	O
▁	O
̣	O
▁ng	O
▁di	O
▁	O
̣	O
▁ch	O
▁vu	O
▁	O
̣	O
▁đa	O
▁	O
̃	O
▁pha	O
▁́	O
▁t	O
▁tri	O
ê	O
▁	O
̉	O
▁n	O
▁cu	O
▁	O
̉	O
▁a	O
▁Công	O
▁ty	O
▁-	O
▁Phát	O
▁triển	O
▁mới	O
▁	O
,	O
▁nâng	O
▁cấp	O
▁ứng	O
▁dụng	O
▁cho	O
▁các	O
▁ngân	O
▁hàng	O
▁trong	O
▁giai	O
▁đoạn	O
▁sắp	O
▁tới	O
▁	O
.	O
▁Your	O
▁skills	O
▁and	O
▁experience	O
▁-	O
▁T	O
ốt	O
▁nghiệp	O
▁Đại	O
▁học	O
▁/	O
▁Cao	O
▁đẳng	O
▁các	O
▁chuyên	O
▁ngành	O
▁Công	O
▁nghệ	O
▁thông	O
▁tin	O
▁	O
,	O
▁Công	O
▁nghệ	O
▁phần	O
▁mềm	O
▁	O
,	O
▁	O
.	O
▁	O
.	O
▁	O
.	O
▁	O
.	O
▁	O
.	O
▁hoặc	O
▁Trường	O
▁đào	O
▁tạo	O
▁lập	O
▁trình	O
▁viên	O
▁Quốc	O
▁Tế	O
▁(	O
▁NI	O
IT	O
▁	O
,	O
▁Ap	O
tech	O
▁)	O
▁trở	O
▁lên	O
▁-	O
▁Có	O
▁từ	O
▁6	O
▁tháng	O
▁kinh	O
▁nghiệm	O
▁trở	O
▁lên	O
▁-	O
▁Hiểu	O
▁biết	O
▁về	O
▁x	B-KNOW
Code	I-KNOW
▁	O
,	O
▁Swift	B-TECH_SKILL
▁	O
,	O
▁có	O
▁kinh	O
▁nghiệm	O
▁lập	O
▁trình	O
▁ứng	O
▁dụng	O
▁trên	O
▁	O
IOS	O
▁-	O
▁Có	O
▁hiểu	O
▁biết	O
▁về	O
▁Real	B-KNOW
m	I-KNOW
▁	O
,	O
▁giao	O
▁tiếp	O
▁client	O
▁–	O
▁server	O
▁thông	O
▁qua	O
▁R	B-KNOW
EST	I-KNOW
▁và	O
▁J	B-KNOW
SON	I-KNOW
▁-	O
▁Có	O
▁kiến	O
▁thức	O
▁về	O
▁Object	O
ive	O
▁–	O
▁C	O
▁là	O
▁1	O
▁lợi	O
▁thế	O
▁	O
,	O
▁chịu	O
▁khó	O
▁học	O
▁hỏi	O
▁	O
,	O
▁tìm	O
▁hiểu	O
▁kiến	O
▁thức	O
▁mới	O
▁-	O
▁Ưu	O
▁tiên	O
▁ứng	O
▁viên	O
▁có	O
▁kinh	O
▁nghiệm	O
▁làm	O
▁về	O
▁lĩnh	O
▁vực	O
▁tài	O
▁chính	O
▁	O
,	O
▁ngân	O
▁hàng	O
▁Why	O
▁you	O
▁'	O
▁	O
ll	O
▁love	O
▁working	O
▁here	O
▁1	O
▁	O
.	O
▁Chế	O
▁độ	O
▁lương	O
▁&	O
▁thưởng	O
▁hấp	O
▁dẫn	O
▁:	O
▁-	O
▁M	O
ức	O
▁lương	O
▁thỏa	O
▁thuận	O
▁theo	O
▁năng	O
▁lực	O
▁	O
,	O
▁đánh	O
▁giá	O
▁năng	O
▁lực	O
▁hàng	O
▁năm	O
▁-	O
▁Chế	O
▁độ	O
▁thưởng	O
▁phong	O
▁phú	O
▁và	O
▁hấp	O
▁dẫn	O
▁(	O
▁Theo	O
▁quy	O
▁định	O
▁và	O
▁chính	O
▁sách	O
▁công	O
▁ty	O
▁)	O
▁-	O
▁Hỗ	O
▁trợ	O
▁ăn	O
▁sáng	O
▁miễn	O
▁phí	O
▁-	O
▁Hỗ	O
▁trợ	O
▁ăn	O
▁trưa	O
▁:	O
▁50	O
▁	O
.	O
▁000	O
đ	O
▁/	O
▁ngày	O
▁-	O
▁Hỗ	O
▁trợ	O
▁gửi	O
▁xe	O
▁	O
,	O
▁xăng	O
▁xe	O
▁	O
,	O
▁điện	O
▁thoại	O
▁(	O
▁tùy	O
▁vị	O
▁trí	O
▁)	O
▁-	O
▁Hỗ	O
▁trợ	O
▁trang	O
▁điểm	O
▁cho	O
▁CB	O
NV	O
▁nữ	O
▁-	O
▁Qu	O
à	O
▁tặng	O
▁các	O
▁ngày	O
▁lễ	O
▁trong	O
▁năm	O
▁2	O
▁	O
.	O
▁Bảo	O
▁hiểm	O
▁&	O
▁chăm	O
▁sóc	O
▁sức	O
▁khỏe	O
▁toàn	O
▁diện	O
▁:	O
▁-	O
▁BH	O
XH	O
▁	O
,	O
▁BH	O
YT	O
▁	O
,	O
▁BH	O
TN	O
▁theo	O
▁pháp	O
▁luật	O
▁hiện	O
▁hành	O
▁-	O
▁G	O
ói	O
▁bảo	O
▁hiểm	O
▁sức	O
▁khỏe	O
▁cao	O
▁cấp	O
▁24	O
▁/	O
▁7	O
▁mua	O
▁cho	O
▁nhân	O
▁viên	O
▁&	O
▁người	O
▁thân	O
▁nhân	O
▁viên	O
▁-	O
▁Khám	O
▁sức	O
▁khỏe	O
▁định	O
▁kỳ	O
▁hàng	O
▁năm	O
▁3	O
▁	O
.	O
▁Mô	O
i	O
▁trường	O
▁làm	O
▁việc	O
▁hiện	O
▁đại	O
▁:	O
▁-	O
▁Cung	O
▁cấp	O
▁máy	O
▁tính	O
▁&	O
▁thiết	O
▁bị	O
▁làm	O
▁việc	O
▁hiện	O
▁đại	O
▁-	O
▁Văn	O
▁phòng	O
▁làm	O
▁việc	O
▁hiện	O
▁đại	O
▁	O
,	O
▁thiết	O
▁bị	O
▁làm	O
▁việc	O
▁Hi	O
▁-	O
▁tech	O
▁-	O
▁Không	O
▁gian	O
▁ăn	O
▁nhẹ	O
▁miễn	O
▁phí	O
▁(	O
▁nước	O
▁uống	O
▁	O
,	O
▁trà	O
▁cafe	O
▁	O
,	O
▁hoa	O
▁quả	O
▁	O
,	O
▁sữa	O
▁chua	O
▁)	O
▁4	O
▁	O
.	O
▁Phát	O
▁triển	O
▁nghề	O
▁nghiệp	O
▁:	O
▁-	O
▁Cơ	O
▁hội	O
▁tiếp	O
▁cận	O
▁với	O
▁những	O
▁công	O
▁nghệ	O
▁mới	O
▁	O
,	O
▁những	O
▁dự	O
▁án	O
▁quy	O
▁mô	O
▁lớn	O
▁-	O
▁Làm	O
▁việc	O
▁cùng	O
▁đội	O
▁ngũ	O
▁hơn	O
▁2000	O
▁nhân	O
▁sự	O
▁tài	O
▁năng	O
▁	O
,	O
▁có	O
▁chuyên	O
▁môn	O
▁giỏi	O
▁	O
,	O
▁dày	O
▁d	O
ặ	O
n	O
▁kinh	O
▁nghiệm	O
▁	O
,	O
▁tư	O
▁duy	O
▁chia	O
▁sẻ	O
▁-	O
▁Được	O
▁tài	O
▁trợ	O
▁kinh	O
▁phí	O
▁tham	O
▁gia	O
▁các	O
▁chương	O
▁trình	O
▁đào	O
▁tạo	O
▁nâng	O
▁cao	O
▁năng	O
▁lực	O
▁-	O
▁Công	O
▁ty	O
▁thành	O
▁lập	O
▁gần	O
▁20	O
▁năm	O
▁với	O
▁các	O
▁sản	O
▁phẩm	O
▁&	O
▁dịch	O
▁vụ	O
▁đã	O
▁được	O
▁k	O
hẳng	O
▁định	O
▁vị	O
▁thế	O
▁trên	O
▁thị	O
▁trường	O
▁5	O
▁	O
.	O
▁Hoạt	O
▁động	O
▁ngoại	O
▁khóa	O
▁phong	O
▁phú	O
▁:	O
▁-	O
▁Văn	O
▁hóa	O
▁công	O
▁ty	O
▁đặc	O
▁sắc	O
▁với	O
▁nhiều	O
▁hoạt	O
▁động	O
▁đoàn	O
▁thể	O
▁được	O
▁quan	O
▁tâm	O
▁đầu	O
▁tư	O
▁:	O
▁Team	O
▁building	O
▁	O
,	O
▁Ngh	O
ỉ	O
▁mát	O
▁(	O
▁trong	O
▁nước	O
▁và	O
▁nước	O
▁ngoài	O
▁)	O
▁	O
,	O
▁20	O
▁/	O
▁10	O
▁	O
,	O
▁Year	O
▁End	O
▁Party	O
▁	O
,	O
▁hoạt	O
▁động	O
▁thiện	O
▁nguyện	O
▁	O
,	O
▁	O
…	O
▁-	O
▁Các	O
▁câu	O
▁lạc	O
▁bộ	O
▁:	O
▁C	O
LB	O
▁Cầu	O
▁lông	O
▁	O
,	O
▁C	O
LB	O
▁Bó	O
ng	O
▁đá	O
▁	O
,	O
▁C	O
LB	O
▁Yoga	O
▁	O
,	O
▁C	O
LB	O
▁Đ	O
iền	O
▁kinh	O
▁	O
,	O
▁C	O
LB	O
▁B	O
ơ	O
i	O
▁Chúng	O
▁tôi	O
▁sẽ	O
▁liên	O
▁hệ	O
▁qua	O
▁điện	O
▁thoại	O
▁với	O
▁những	O
▁CV	O
▁phù	O
▁hợp	O
▁trong	O
▁vòng	O
▁7	O
▁ngày	O
▁làm	O
▁việc	O
▁kể	O
▁từ	O
▁ngày	O
▁ứng	O
▁tuyển	O
▁	O
.	O
▁Lưu	O
▁ý	O
▁:	O
▁Công	O
▁ty	O
▁đang	O
▁tuyển	O
▁tại	O
▁2	O
▁văn	O
▁phòng	O
▁Hà	O
▁Nội	O
▁và	O
▁Tp	O
▁	O
.	O
▁Hồ	O
▁Chí	O
▁Minh	O
▁	O
,	O
▁ứng	O
▁viên	O
▁vui	O
▁lòng	O
▁ghi	O
▁rõ	O
▁địa	O
▁chỉ	O
▁trên	O
▁CV	O
▁	O
.	O
</s>	None

In [ ]:
def tokenize_fn_with_stride(batch):
    tokens_batch = [item["tokens"] for item in batch["parse_bio"]]
    ner_tags_batch = [item["ner_tags"] for item in batch["parse_bio"]]

    tokenized_inputs = tokenizer(
        tokens_batch,
        truncation=True,
        max_length=512,
        stride=50,
        return_overflowing_tokens=True,
        is_split_into_words=True,
    )

    aligned_targets_batch = []
    sample_mapping = tokenized_inputs.pop("overflow_to_sample_mapping")

    for chunk_index, original_sample_index in enumerate(sample_mapping):
        original_labels = ner_tags_batch[original_sample_index]
        word_ids = tokenized_inputs.word_ids(chunk_index)
        aligned_targets_batch.append(align_target(original_labels, word_ids))

    tokenized_inputs["labels"] = aligned_targets_batch
    return tokenized_inputs

In [ ]:
from datasets import Dataset

RANDOM_SEED = 42
EVAL_SIZE = 0.2

unique_job_ids = train_df["job_id"].drop_duplicates()
eval_job_ids = set(unique_job_ids.sample(frac=EVAL_SIZE, random_state=RANDOM_SEED))

train_raw_df = train_df[~train_df["job_id"].isin(eval_job_ids)].reset_index(drop=True)
eval_raw_df = train_df[train_df["job_id"].isin(eval_job_ids)].reset_index(drop=True)

train_job_ids = set(train_raw_df["job_id"])
eval_job_ids = set(eval_raw_df["job_id"])
assert train_job_ids.isdisjoint(eval_job_ids), "job_id leakage between train/eval"

print({
    "train_rows": len(train_raw_df),
    "eval_rows": len(eval_raw_df),
    "train_job_ids": len(train_job_ids),
    "eval_job_ids": len(eval_job_ids),
})


def dataset_ready_df(df):
    df = df.copy()
    df["parse_bio"] = df["parse_bio"].apply(
        lambda item: {
            "tokens": item["tokens"],
            "ner_tags": item["ner_tags"],
        }
    )
    return df

train_dataset_raw = Dataset.from_pandas(dataset_ready_df(train_raw_df), preserve_index=False)
eval_dataset_raw = Dataset.from_pandas(dataset_ready_df(eval_raw_df), preserve_index=False)

train_dataset = train_dataset_raw.map(
    tokenize_fn_with_stride,
    batched=True,
    remove_columns=list(train_raw_df.columns),
)
eval_dataset = eval_dataset_raw.map(
    tokenize_fn_with_stride,
    batched=True,
    remove_columns=list(eval_raw_df.columns),
)

tokenized_dataset = train_dataset

Map:   0%|          | 0/1770 [00:00<?, ? examples/s]

In [ ]:
from transformers import DataCollatorForTokenClassification

# Create a DataCollatorForTokenClassification object
data_collator = DataCollatorForTokenClassification(tokenizer=tokenizer)

# Testing data using the data collator
batch = data_collator([tokenized_dataset[i] for i in range(2)])

# Display the resulting batch
batch

{'input_ids': tensor([[     0,  99321,   3529,   5152,   9442,      6,      4,  14948,  13291,
            544,  16969,  45645,   7099,  10657,   4420,   3611,   6567, 145581,
           3790,  14469,  75896,  11948,  22584,      7,      6,      5,  38465,
           8130,      6,      4,   9442,  18960,    544,  13697,   3903,   9828,
           4746,  31281,   2479,    984,  11050,    544,  96305,   3196,   1636,
             15,    472,   1019,      7,   1388,      6,      5,    384,  10767,
           3822,  61687,      6,      4,  21785,  41038,   9432,   6842,   5587,
           7099,  10657,    544,  28085,   3903,  67885,  11154,   7976,      6,
              5, 172102,     14,   3822,   1116,  42106,   5152,   9442,   3989,
           5692,   1498,  14346,   3822,    925,   3989,   5692,  44565,   2249,
            925,  13932,   2786,   3839, 191864,  33918,    681,   6122,  35813,
              6,      4,   7378,   3178,      6,      4,      6,      5,      6,
              5,      6,      5,      6,      5,      2,      1,      1,      1,
              1,      1,      1,      1,      1,      1,      1,      1,      1,
              1,      1,      1,      1,      1,      1,      1,      1,      1,
              1,      1,      1,      1,      1,      1,      1,      1,      1,
              1,      1,      1,      1,      1,      1,      1,      1,      1,
              1,      1,      1,      1,      1,      1,      1,      1,      1,
              1,      1,      1,      1,      1,      1,      1,      1,      1,
              1,      1,      1,      1,      1,      1,      1,      1,      1,
              1,      1,      1,      1,      1,      1,      1,      1,      1,
              1,      1,      1,      1,      1,      1,      1,      1,      1,
              1,      1,      1,      1,      1,      1,      1,      1,      1,
              1,      1,      1,      1,      1,      1,      1,      1,      1,
              1,      1,      1,      1,      1,      1,      1,      1,      1,
              1,      1,      1,      1,      1,      1,      1,      1,      1,
              1,      1,      1,      1,      1,      1,      1,      1,      1,
              1,      1,      1,      1,      1,      1,      1,      1,      1,
              1,      1,      1,      1,      1,      1,      1,      1,      1,
              1,      1,      1,      1,      1,      1,      1,      1,      1,
              1,      1,      1,      1,      1,      1,      1,      1,      1,
              1,      1,      1,      1,      1,      1,      1,      1,      1,
              1,      1,      1,      1,      1,      1,      1,      1,      1,
              1,      1,      1,      1,      1,      1,      1,      1,      1,
              1,      1,      1,      1,      1,      1,      1,      1,      1,
              1,      1,      1,      1,      1,      1],
        [     0,   2777,    133,   9578,  22751,   1401,    621, 191618,     10,
         167729,    297,    136,  22443,     20,  23509,    297,  75344,    913,
           4935, 125362,   5337,     19,     47,  33284,   2446, 145666,    939,
           1310,   3984,  42991, 125362,    262,   1042,      6,      5,    581,
          38478,   1221,   8060,     70,  88779,   5844,  71702,   7175,     23,
          25188,    214,      6,      4,   4420,   6954,    214,      6,      4,
            136,   7968,     53,  35401,  71702,  50531,      7,      6,      4,
          20697,  20903,    538,    678,  55230,  25188,   1314,    136, 188535,
              7,      6,      5,   3293,  31486,  64600,  44540,     20,     98,
         197826,     47,  88779,   5844,  71702,   4488, 118664,      7,  17368,
           2773,  16839,   2053,      6,      5,  26824,      6,  94399,  36584,
           2449,  11809, 116548,   1363,    619, 114837,    164,  58832,     70,
           4173,  10763,      6,      4, 174033,      6,      4,    136, 212485,
            111,   1733,     20,  36549,  53477,   2053,     15,  31837,      7,
              6,      4,  22690,      7,      6,      4, 183594,      7,   1388,
          17368,  80866,    136, 145581,      6,      5,  54360,     23,     22,
              7,  53089,   2053,  31897,    100,   4420,   6954,    214,      6,
              4,  26719,  45064, 132283, 142424,    136,  62822,   2053,     23,
          25553,   6892,  58732,      6,      5,  26828,   6954,    214,    619,
           7832,     67,   3432,  58832,  54360,     23,  29479,    214,    136,
         134234,  88779,   5844,  71702,  50531,      7,     15,     28,      6,
              5,    706,      6,      5,   3095,    316,      6,      4,  29459,
             20,    456,  46354,      6,      4,  12768,     20,  25632,   1388,
          17368, 145581,      6,      5,  28398,   4420,   6954,    214,  40226,
           5256,    136,   4358, 151575,     13, 113857, 123166,  36880,  12921,
          16839,  27289,      6,      5,  94030, 151228,   1363,    619,  43101,
           2320,  33326,     53,    731,  22799,  23718,  27079,   4439,     15,
             28,      6,      5,    706,      6,      5,  30646,      6,      4,
         174048,   2481,      6,      4,  79442,  34695,      6,      4,  10512,
             20, 126596,    297,  23718,   1388,      6,      5, 131150,  14096,
             13,   4420,   6954,    214,  50339,    136, 150556,      7,     23,
          34735, 117729,     47,   8060,  35107,      7,    678,  22962,  55230,
              7,    136, 188535,      7,      6,      5,  13293,  25447,     85,
           1363,  58832,  54360,    678,  62822,  60627,   7432,  12765,      7,
            136, 171859,      6, 176302,   2481, 114137,   1379, 196219,   1295,
             70,  55230,   7175,      6,      5,      2]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1]]), 'labels': tensor([[-100,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    1,    0,    0,    0,    1,    2,    2,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    1,    2,    0,    1,    2,    2,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0, -100, -100, -100, -100, -100, -100, -100,
         -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
         -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
         -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
         -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
         -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
         -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
         -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
         -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
         -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
         -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
         -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
         -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
         -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
         -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
         -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
         -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
         -100, -100, -100, -100, -100, -100, -100, -100, -100],
        [-100,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    3,    4,    4,    4,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    3,    4,    4,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    3,
            4,    4,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    1,    0,    1,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    3,    4,    4,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    1,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0, -100]])}

In [ ]:
!pip install evaluate seqeval

Collecting evaluate
  Downloading evaluate-0.4.6-py3-none-any.whl.metadata (9.5 kB)
Collecting seqeval
  Downloading seqeval-1.2.2.tar.gz (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.6/43.6 kB 4.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: datasets>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (4.0.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.0.2)
Requirement already satisfied: dill in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.2.2)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.32.4)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.12/dist-packages (from evaluate) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from evaluate) (3.6.0)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.70.16)
Requirement already satisfied: fsspec>=2021.05.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (1.11.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from evaluate) (26.1)
Requirement already satisfied: scikit-learn>=0.21.3 in /usr/local/lib/python3.12/dist-packages (from seqeval) (1.6.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (3.29.0)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (18.1.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (3.13.5)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (0.28.1)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (0.24.2)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (2026.4.22)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.21.3->seqeval) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.21.3->seqeval) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.21.3->seqeval) (3.6.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2026.1)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.23.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.7.0->evaluate) (4.13.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.7.0->evaluate) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.7.0->evaluate) (0.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->evaluate) (1.17.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.7.0->evaluate) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.7.0->evaluate) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.7.0->evaluate) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.7.0->evaluate) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.7.0->evaluate) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.7.0->evaluate) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub>=0.7.0->evaluate) (0.1.2)
Downloading evaluate-0.4.6-py3-none-any.whl (84 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 8.8 MB/s eta 0:00:00
Building wheels for collected packages: seqeval
  Building wheel for seqeval (setup.py) ... done
  Created wheel for seqeval: filename=seqeval-1.2.2-py3-none-any.whl size=16162 sha256=9dba1cfca28dc2d8655d5e7d7024a45c7fc81917e925675a142098ae2b0aa401
  Stored in directory: /root/.cache/pip/wheels/5f/b8/73/0b2c1a76b701a677653dd79ece07cfabd7457989dbfbdcd8d7
Successfully built seqeval
Installing collected packages: seqeval, evaluate
Successfully installed evaluate-0.4.6 seqeval-1.2.2

In [ ]:
from evaluate import load

# Load the seqeval metric which can evaluate NER and other sequence tasks
metric = load("seqeval")

# Example usage: compute metric on a sample predictions and reference list
# predictions and references should be a list of lists containing predicted and true token labels

# List of List Input
metric.compute(predictions = [['O' , 'B-LANG' , 'I-LANG']],
               references = [['O' , 'B-TECH' , 'I-TECH']])

Downloading builder script: 0.00B [00:00, ?B/s]

/usr/local/lib/python3.12/dist-packages/seqeval/metrics/v1.py:57: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.12/dist-packages/seqeval/metrics/v1.py:57: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

{'LANG': {'precision': np.float64(0.0),
  'recall': np.float64(0.0),
  'f1': np.float64(0.0),
  'number': np.int64(0)},
 'TECH': {'precision': np.float64(0.0),
  'recall': np.float64(0.0),
  'f1': np.float64(0.0),
  'number': np.int64(1)},
 'overall_precision': np.float64(0.0),
 'overall_recall': np.float64(0.0),
 'overall_f1': np.float64(0.0),
 'overall_accuracy': 0.3333333333333333}

In [ ]:
import numpy as np


def compute_metrics(logits_and_labels):
    logits, labels = logits_and_labels
    predictions = np.argmax(logits, axis=-1)

    str_labels = [
        [label_names[token_label] for token_label in label if token_label != -100]
        for label in labels
    ]
    str_preds = [
        [label_names[pred] for pred, token_label in zip(prediction, label) if token_label != -100]
        for prediction, label in zip(predictions, labels)
    ]

    results = metric.compute(predictions=str_preds, references=str_labels, zero_division=0)
    metrics = {
        "precision": results["overall_precision"],
        "recall": results["overall_recall"],
        "f1": results["overall_f1"],
        "accuracy": results["overall_accuracy"],
    }

    for entity_name in ["TECH_SKILL", "KNOW"]:
        if entity_name in results:
            metrics[f"{entity_name}_precision"] = results[entity_name]["precision"]
            metrics[f"{entity_name}_recall"] = results[entity_name]["recall"]
            metrics[f"{entity_name}_f1"] = results[entity_name]["f1"]
            metrics[f"{entity_name}_number"] = results[entity_name]["number"]

    return metrics

In [ ]:
# Create mapping from label ID to label string name
id2label = {k: v for k, v in enumerate(label_names)}

# Create reverse mapping from label name to label ID
label2id = {v: k for k, v in enumerate(label_names)}

print(id2label , '\n--------------------\n' , label2id)

{0: 'O', 1: 'B-TECH_SKILL', 2: 'I-TECH_SKILL ', 3: 'B-KNOW', 4: 'I-KNOW'}
--------------------
 {'O': 0, 'B-TECH_SKILL': 1, 'I-TECH_SKILL ': 2, 'B-KNOW': 3, 'I-KNOW': 4}

In [ ]:
# Load pretrained token classification model from Transformers
from transformers import AutoModelForTokenClassification

# Initialize model object with pretrained weights
model = AutoModelForTokenClassification.from_pretrained(
  checkpoint,

  # Pass in label mappings
  id2label=id2label,
  label2id=label2id
)

model.safetensors:   0%|          | 0.00/1.12G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

XLMRobertaForTokenClassification LOAD REPORT from: xlm-roberta-base
Key                         | Status     |
----------------------------+------------+-
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
roberta.pooler.dense.weight | UNEXPECTED |
roberta.pooler.dense.bias   | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
classifier.bias             | MISSING    |
classifier.weight           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [ ]:
from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir="/content/drive/MyDrive/Classroom/DATN/Model/fine_tuned_model_NER_03_05_2",
    eval_strategy="epoch",
    save_strategy="epoch",
    logging_strategy="steps",
    logging_steps=25,
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=8,
    weight_decay=0.01,
    load_best_model_at_end=True,
    metric_for_best_model="f1",
    greater_is_better=True,
    save_total_limit=2,
    seed=RANDOM_SEED,
    data_seed=RANDOM_SEED,
)

In [ ]:
from transformers import EarlyStoppingCallback, Trainer

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=eval_dataset,
    compute_metrics=compute_metrics,
    data_collator=data_collator,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=2)],
)

In [ ]:
import numpy as np

In [ ]:
trainer.train()

/usr/local/lib/python3.12/dist-packages/seqeval/metrics/v1.py:57: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=273, training_loss=0.2204876714573675, metrics={'train_runtime': 415.2087, 'train_samples_per_second': 10.426, 'train_steps_per_second': 0.658, 'total_flos': 900186128079030.0, 'train_loss': 0.2204876714573675, 'epoch': 3.0})

In [ ]:
eval_predictions = trainer.predict(eval_dataset)
eval_logits, eval_labels = eval_predictions.predictions, eval_predictions.label_ids
eval_pred_ids = np.argmax(eval_logits, axis=-1)

eval_label_names = [
    [label_names[token_label] for token_label in label if token_label != -100]
    for label in eval_labels
]
eval_pred_names = [
    [label_names[pred] for pred, token_label in zip(prediction, label) if token_label != -100]
    for prediction, label in zip(eval_pred_ids, eval_labels)
]

classification_report = metric.compute(
    predictions=eval_pred_names,
    references=eval_label_names,
    zero_division=0,
)
classification_report

In [ ]:
def bio_entities(labels):
    entities = []
    start = None
    entity_type = None

    for index, label in enumerate(labels + ["O"]):
        if label == "O":
            if entity_type is not None:
                entities.append((entity_type, start, index))
                start = None
                entity_type = None
            continue

        prefix, current_type = label.split("-", 1)
        if prefix == "B" or current_type != entity_type:
            if entity_type is not None:
                entities.append((entity_type, start, index))
            start = index
            entity_type = current_type

    return entities


error_rows = []
for row_idx, (gold_labels, pred_labels) in enumerate(zip(eval_label_names, eval_pred_names)):
    if gold_labels == pred_labels:
        continue
    error_rows.append({
        "row_idx": row_idx,
        "gold_entities": bio_entities(gold_labels),
        "pred_entities": bio_entities(pred_labels),
        "gold_labels": gold_labels,
        "pred_labels": pred_labels,
    })

error_df = pd.DataFrame(error_rows)
error_path = "/content/drive/MyDrive/Classroom/DATN/Model/ner_eval_errors.csv"
error_df.to_csv(error_path, index=False)
print({"error_rows": len(error_df), "error_path": error_path})
error_df.head(20)

In [ ]:
!pip install sentencepiece

Requirement already satisfied: sentencepiece in /usr/local/lib/python3.12/dist-packages (0.2.1)

In [ ]:
from transformers import AutoTokenizer, AutoModelForTokenClassification, pipeline

# Prefer trainer.state.best_model_checkpoint after training. Fallback keeps manual reload possible.
model_path = trainer.state.best_model_checkpoint or "/content/drive/MyDrive/Classroom/DATN/Model/fine_tuned_model_NER_03_05/checkpoint-273"
print("Loading model from:", model_path)

loaded_tokenizer = AutoTokenizer.from_pretrained(model_path)
label_names = ["O", "B-TECH_SKILL", "I-TECH_SKILL", "B-KNOW", "I-KNOW"]
id2label = {i: label for i, label in enumerate(label_names)}
label2id = {label: i for i, label in enumerate(label_names)}

loaded_model = AutoModelForTokenClassification.from_pretrained(
    model_path,
    id2label=id2label,
    label2id=label2id,
)

explicit_ner_pipeline = pipeline(
    "token-classification",
    model=loaded_model,
    tokenizer=loaded_tokenizer,
    aggregation_strategy="simple",
    device=-1,
)

print("Model and tokenizer loaded successfully.")

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Model and tokenizer loaded successfully using AutoModel and AutoTokenizer!

In [ ]:
test_inf_text = """
Có từ 1 năm kinh nghiệm trở lên làm việc với Python. Có kinh nghiệm làm với framework: Django, Flask, FastAPI Có khả năng triển khai cả Backend và Frontend trong các dự án web/app. Hiểu biết về cơ sở dữ liệu (MySQL, PostgreSQL hoặc tương đương). Nắm vững kiến thức về kiến trúc phần mềm, mô hình MVC và RESTful API. Có khả năng phân tích, thiết kế và xây dựng hệ thống phần mềm. Thành thạo kỹ năng giải quyết vấn đề, tư duy logic và có khả năng làm việc độc lập hoặc theo nhóm. Ưu tiên ứng viên có nền tảng lập trình vững, sẵn sàng làm việc với đa ngôn ngữ (Python, JavaScript, ...) Có khả năng giao tiếp tốt, làm việc nhóm hiệu quả và chủ động học hỏi, cập nhật công nghệ mới. Biết quản lý thời gian, sắp xếp công việc khoa học và theo sát tiến độ dự án.
"""

In [ ]:
# Example usage with the explicit pipeline
sample_text = test_inf_text
predictions = explicit_ner_pipeline(sample_text)

# Print the predic
tions
import pprint
pprint.pprint(predictions)

[{'end': 110,
  'entity_group': 'TECH_SKILL ',
  'score': np.float32(0.8133003),
  'start': 103,
  'word': 'FastAPI'},
 {'end': 227,
  'entity_group': 'TECH_SKILL ',
  'score': np.float32(0.8157747),
  'start': 217,
  'word': 'PostgreSQL'},
 {'end': 311,
  'entity_group': 'TECH_SKILL ',
  'score': np.float32(0.61230475),
  'start': 304,
  'word': 'RESTful'}]