In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../../../data/job_descriptions.csv')

In [3]:
df

,title,company,company_image_url,location,description,site,job_url,it_role_type,main_programming_languages,key_technologies,city
0,iOS Developer (Swift),VNPAY,https://itviec.com/rails/active_storage/repres...,"22 Láng Hạ, Dong Da, Ha Noi; Tầng 12, tòa nhà...",Top 3 reasons to join us\n- Lương và chế độ hấ...,ITViec,https://itviec.com/it-jobs/ios-developer-swift...,Mobile Developer,['Swift'],"['xCode', 'Realm', 'REST', 'JSON', 'Objective-C']",Hà Nội
1,"5 Fullstack Dev (Java, Spring, Angular)",LEAP,https://itviec.com/rails/active_storage/repres...,"199 Dien Bien Phu, Binh Thanh, Ho Chi Minh",Top 3 reasons to join us\n- 18+ days of annual...,ITViec,https://itviec.com/it-jobs/5-fullstack-dev-jav...,Full-stack Developer,"['Java', 'JavaScript', 'HTML/CSS']","['Spring Boot', 'Angular', 'React', 'Agile']",Hồ Chí Minh
2,"Mid/Senior Frontend Developer (Next.js, Tailwi...","Local Life Technology Ltd.,",https://itviec.com/rails/active_storage/repres...,"63 Nguyễn Hiến Lê, phường Hoà Xuân, Cam Le, Da...",LocalLife.Asia là nền tảng kết nối du khách vớ...,ITViec,https://itviec.com/it-jobs/mid-senior-frontend...,Frontend Developer,['TypeScript'],"['Next.js', 'Tailwind CSS']",Đà Nẵng
3,"Atlassian ITSM Development Engineer (ITSM, Pyt...",TymeX,https://itviec.com/rails/active_storage/repres...,"Level 5 - 6, East Tower, Lumiere Riverside, 27...",TymeX is an innovative digital banking develop...,ITViec,https://itviec.com/it-jobs/atlassian-itsm-deve...,ITSM Development Engineer,['Python'],"['JIRA Service Management', 'Confluence', 'Ops...",Hồ Chí Minh
4,Junior QC Engineer (Tester/QA QC),Fastboy Marketing,https://itviec.com/rails/active_storage/repres...,"56A Le Khoi, Phu Thanh, Tan Phu, Ho Chi Minh",We are building an environment where personal ...,ITViec,https://itviec.com/it-jobs/junior-qc-engineer-...,QA Engineer,[],"['Agile', 'Automated Testing', 'Performance Te...",Hồ Chí Minh
...,...,...,...,...,...,...,...,...,...,...,...
3096,Fullstack Web Developer,CÔNG TY TNHH ROYALMAN,https://cdn-new.topcv.vn/unsafe/80x/https://st...,"Hồ Chí Minh, Quận 7",Mô tả công việc\n- Being part of the VN Softwa...,TopCV,https://www.topcv.vn/viec-lam/fullstack-web-de...,Fullstack Developer,"['JavaScript', 'NodeJS']","['React', 'AWS', 'Google Cloud', 'Kafka', 'Doc...",Hồ Chí Minh
3097,Backend Developer (AWS),Công Ty Cổ Phần Vàng Bạc Đá quý Phú Nhuận - PNJ,https://cdn-new.topcv.vn/unsafe/80x/https://st...,Hồ Chí Minh,Mô tả công việc\n- Develop and maintain high-p...,TopCV,https://www.topcv.vn/viec-lam/backend-develope...,Backend Developer,"['Python', 'Node.js']","['AWS', 'Serverless Architecture', 'CI/CD', 'I...",Hồ Chí Minh
3098,Lập Trình Wordpress Developer,Công ty TNHH Đầu tư Thương Mại Flexhouse,https://cdn-new.topcv.vn/unsafe/80x/https://st...,Hồ Chí Minh,"• Thiết kế, lập trình và phát triển các websit...",TopCV,https://www.topcv.vn/viec-lam/lap-trinh-wordpr...,Backend Developer,"['PHP', 'HTML', 'CSS', 'JavaScript', 'SQL']","['WordPress', 'SEO', 'Git']",Hồ Chí Minh
3099,Phần Mềm,Công ty TNHH Med-Aid,https://www.topcv.vn/v4/image/normal-company/l...,Hà Nội,Mô tả công việc\n1. Phát triển và tích hợp hệ ...,TopCV,https://www.topcv.vn/viec-lam/phan-mem/1761008...,Full-stack Developer,"['Python', 'C', 'JavaScript']","['Django', 'FastAPI', 'Flask', 'React', 'Flutt...",Hà Nội
3100,Kỹ Sư Lập Trình Đứng Máy Phay CNC,CÔNG TY CỔ PHẦN DHNTECH VIỆT NAM,https://cdn-new.topcv.vn/unsafe/80x/https://st...,Hà Nội,Mô tả công việc\n- Lập trình gia công trên phầ...,TopCV,https://www.topcv.vn/viec-lam/ky-su-lap-trinh-...,Other IT Role,[],"['Mastercam', 'NX', 'Powermill', 'SolidWorks',...",Hà Nội

In [4]:
import ast
def parse_key_technology(key_technology_str):
    try:
        return ast.literal_eval(key_technology_str)
    except (ValueError, SyntaxError):
        return []
    

df['key_technologies'] = df['key_technologies'].apply(parse_key_technology)

In [5]:
df

,title,company,company_image_url,location,description,site,job_url,it_role_type,main_programming_languages,key_technologies,city
0,iOS Developer (Swift),VNPAY,https://itviec.com/rails/active_storage/repres...,"22 Láng Hạ, Dong Da, Ha Noi; Tầng 12, tòa nhà...",Top 3 reasons to join us\n- Lương và chế độ hấ...,ITViec,https://itviec.com/it-jobs/ios-developer-swift...,Mobile Developer,['Swift'],"[xCode, Realm, REST, JSON, Objective-C]",Hà Nội
1,"5 Fullstack Dev (Java, Spring, Angular)",LEAP,https://itviec.com/rails/active_storage/repres...,"199 Dien Bien Phu, Binh Thanh, Ho Chi Minh",Top 3 reasons to join us\n- 18+ days of annual...,ITViec,https://itviec.com/it-jobs/5-fullstack-dev-jav...,Full-stack Developer,"['Java', 'JavaScript', 'HTML/CSS']","[Spring Boot, Angular, React, Agile]",Hồ Chí Minh
2,"Mid/Senior Frontend Developer (Next.js, Tailwi...","Local Life Technology Ltd.,",https://itviec.com/rails/active_storage/repres...,"63 Nguyễn Hiến Lê, phường Hoà Xuân, Cam Le, Da...",LocalLife.Asia là nền tảng kết nối du khách vớ...,ITViec,https://itviec.com/it-jobs/mid-senior-frontend...,Frontend Developer,['TypeScript'],"[Next.js, Tailwind CSS]",Đà Nẵng
3,"Atlassian ITSM Development Engineer (ITSM, Pyt...",TymeX,https://itviec.com/rails/active_storage/repres...,"Level 5 - 6, East Tower, Lumiere Riverside, 27...",TymeX is an innovative digital banking develop...,ITViec,https://itviec.com/it-jobs/atlassian-itsm-deve...,ITSM Development Engineer,['Python'],"[JIRA Service Management, Confluence, Opsgenie...",Hồ Chí Minh
4,Junior QC Engineer (Tester/QA QC),Fastboy Marketing,https://itviec.com/rails/active_storage/repres...,"56A Le Khoi, Phu Thanh, Tan Phu, Ho Chi Minh",We are building an environment where personal ...,ITViec,https://itviec.com/it-jobs/junior-qc-engineer-...,QA Engineer,[],"[Agile, Automated Testing, Performance Testing...",Hồ Chí Minh
...,...,...,...,...,...,...,...,...,...,...,...
3096,Fullstack Web Developer,CÔNG TY TNHH ROYALMAN,https://cdn-new.topcv.vn/unsafe/80x/https://st...,"Hồ Chí Minh, Quận 7",Mô tả công việc\n- Being part of the VN Softwa...,TopCV,https://www.topcv.vn/viec-lam/fullstack-web-de...,Fullstack Developer,"['JavaScript', 'NodeJS']","[React, AWS, Google Cloud, Kafka, Docker, Rabb...",Hồ Chí Minh
3097,Backend Developer (AWS),Công Ty Cổ Phần Vàng Bạc Đá quý Phú Nhuận - PNJ,https://cdn-new.topcv.vn/unsafe/80x/https://st...,Hồ Chí Minh,Mô tả công việc\n- Develop and maintain high-p...,TopCV,https://www.topcv.vn/viec-lam/backend-develope...,Backend Developer,"['Python', 'Node.js']","[AWS, Serverless Architecture, CI/CD, Infrastr...",Hồ Chí Minh
3098,Lập Trình Wordpress Developer,Công ty TNHH Đầu tư Thương Mại Flexhouse,https://cdn-new.topcv.vn/unsafe/80x/https://st...,Hồ Chí Minh,"• Thiết kế, lập trình và phát triển các websit...",TopCV,https://www.topcv.vn/viec-lam/lap-trinh-wordpr...,Backend Developer,"['PHP', 'HTML', 'CSS', 'JavaScript', 'SQL']","[WordPress, SEO, Git]",Hồ Chí Minh
3099,Phần Mềm,Công ty TNHH Med-Aid,https://www.topcv.vn/v4/image/normal-company/l...,Hà Nội,Mô tả công việc\n1. Phát triển và tích hợp hệ ...,TopCV,https://www.topcv.vn/viec-lam/phan-mem/1761008...,Full-stack Developer,"['Python', 'C', 'JavaScript']","[Django, FastAPI, Flask, React, Flutter, RESTf...",Hà Nội
3100,Kỹ Sư Lập Trình Đứng Máy Phay CNC,CÔNG TY CỔ PHẦN DHNTECH VIỆT NAM,https://cdn-new.topcv.vn/unsafe/80x/https://st...,Hà Nội,Mô tả công việc\n- Lập trình gia công trên phầ...,TopCV,https://www.topcv.vn/viec-lam/ky-su-lap-trinh-...,Other IT Role,[],"[Mastercam, NX, Powermill, SolidWorks, AutoCAD]",Hà Nội

In [6]:
key_tech_series = df['key_technologies'].explode().reset_index(drop=True)
key_tech_series = key_tech_series.dropna()
key_tech_df = key_tech_series.to_frame(name='key_technologies')

In [7]:
key_tech_df

      key_technologies
0                xCode
1                Realm
2                 REST
3                 JSON
4          Objective-C
...                ...
16441        Mastercam
16442               NX
16443        Powermill
16444       SolidWorks
16445          AutoCAD

[16223 rows x 1 columns]

In [8]:
unique_key_technologies_df = key_tech_df["key_technologies"].str.strip().str.lower().drop_duplicates()

In [9]:
unique_key_technologies_df

0                    xcode
1                    realm
2                     rest
3                     json
4              objective-c
               ...
16037       openid connect
16049         api services
16226    visual studio.net
16295                netty
16296          apache mina
Name: key_technologies, Length: 1736, dtype: object

In [10]:
unique_key_technologies_df.to_csv('../../../data/ready_data/unique_key_technologies.csv', index=False)